Global-API/importer/climatetrace_importer.py
Global-API/schema/README.md
Global-API/schema/asset.py
Global-API/schema/base.py
Global-API/schema/create_database.py

This code creates the PostgreSQL database for the global API. Specifically, `create_database.py` creates an `Asset` table to hold raw un-processed ClimateTRACE data. The database parameters will be defined as GitHub Secrets

ON-682: Set up the Postgres database schema

---

emissions_factors/data_processed/EFDB_US/Publisher.csv
emissions_factors/scripts/EFDB_US.py

fixes a typo. changes `publisher_name` to `name` in the `Publisher` table. 
The  [lucid chart](https://lucid.app/lucidchart/7a94c7ce-1b2c-49ec-863b-a2e928ca119f/edit?invitationId=inv_1de91863-7a10-460b-bcfe-3a93f970252d&referringApp=slack&page=0_0#) listed the column as `publisher_name`, I have updated the diagram so it now agrees with the database.

fix: change publisher_name to name in Publisher table

---

app/migrations/20230906193347-modify-EmissionsFactor.cjs

This adds the following columns to the `EmissionsFactor` table:
-  `gpc_refno`: GPC reference number
- `gas`: chemical formula of the gas
- `region`: region code the EF is applicable for (eg. CA) [optional]
- `time_frame`: time frame the EF is applicable for (eg 2010)  [optional]
- `reference`: reference for the EF [optional] 
This should be enough to uniquely define the emissions factor. Please let me know if any changes are necessary.

feat(ON-774): add new migration to CC EmissionsFactor

---

global-api/migrations/versions/64eb87bae0a3_add_edgar_tables.py

this adds three tables to the ccglobal API Database. I named them to be specifically used for [EDGAR data](https://edgar.jrc.ec.europa.eu/dataset_ghg70#p3), but they may generalizable. This PR adds three tables:
- `edgar_grid`: this contains relevant grid information (centroid, polygon in WKT, and area)
- `edgar_data`: this contains the emissions data for each gas. The corresponding GPC reference number is included and there is a FK to `edgar_grid`
- `edgar_city_data`: this contains the fraction of each grid cell that is within each locode. Only grid cells where the fraction is >0 will be included.
`edgar_data` contains all the raw data, so this could be used for custom boundaries. While `edgar_city_data` contains the fractions of grid cells within the locode geometries we got from OSM.

feat(ON-809): add EDGAR tables to ccglobal API database

---

global-api/main.py
global-api/routes/city_locode_endpoint_edgar.py

this PR adds a get endpoint to the global API.
This was tested locally. 
`http://localhost:8000/api/v0/edgar/city/US NYC/2021/II.1.1`
returns:
```json
{
"totals": {
"totals": {
"emissions": {
"co2_mass": "266468760",
"co2_co2eq": "266468760",
"ch4_mass": "21810",
"ch4_co2eq_100yr": "649938.0",
"ch4_co2eq_20yr": "1799325.0",
"n2o_mass": "11951",
"n2o_co2eq_100yr": "3262623",
"n2o_co2eq_20yr": "3262623",
"gpc_quality": "TBD"
}
}
}
}
```

ON-840: add EDGAR endpoint to global API

---

app/migrations/20231024111822-user-default-inventory.cjs
app/package-lock.json
app/package.json
app/src/app/[lng]/onboarding/setup/page.tsx
app/src/app/[lng]/page.tsx
app/src/app/api/v0/city/[city]/inventory/[year]/route.ts
app/src/app/api/v0/city/route.ts
app/src/app/api/v0/user/route.ts
app/src/components/CityMap.tsx
app/src/lib/auth.ts
app/src/models/User.ts
app/src/services/api.ts
app/src/util/api.ts
app/src/util/types.d.ts
app/tests/api/city.test.ts
app/tests/api/inventory.test.ts
app/tests/api/sector.test.ts
app/tests/api/subsector.test.ts
app/tests/api/user.test.ts
app/tests/helpers.ts

- Store `defaultCityLocode` and `defaultInventoryYear` in `User` model
- Save this information when creating a new inventory during onboarding
- Load it on dashboard
- Show city name and country flag on dashboard heading
- Fix TypeScript ESModule related errors in tests (couldn't import Credentials in auth.ts)
- Mock useServerSession in tests since headers()/ async storage isn't available without a server
- Add better error handling to onboarding setup page (with toast popups)
- Ignore city unique error on onboarding setup, since we can just create the inventory then
- Actually create an inventory, not just a city on onboarding setup page
- Redirect to onboarding when a user doesn't have a defaultCityLocode/ defaultInventoryYear assigned yet

Add default inventory storage

---

global-api/importer/edgar/citycelloverlapedgar_importer.py
global-api/importer/edgar/gridcellemissionsedgar_importer.py

This PR removes the use of `.astype()` which was causing the importer not to run for some reason.

fix(edgar-importer): remove astype() from importer

---

app/migrations/20231206143948-SubSectorValue-unique.cjs
app/src/app/[lng]/data/[step]/SubsectorDrawer.tsx
app/src/app/[lng]/data/[step]/page.tsx
app/src/app/api/v0/city/[city]/inventory/[year]/progress/route.ts
app/src/app/api/v0/inventory/[inventory]/subcategory/[subcategory]/route.ts
app/src/util/helpers.ts
app/tests/api/subsector.test.ts

- Adds unique constraint (and index) on SubSectorValue table for `(inventory_id, subsector_id)` to prevent multiple values being saved for a single inventory
- Fixes race condition for API requests during add data form saving by saving the SubCategoryValue instances one after another (for now, there can be a batch endpoint later)
- This deletes all current SubSectorValue entries to prevent issues during the migration. Do I need to delete the SubCategoryValues as well so we don't have left-over data in the DB? Or is it fine since these tables will be removed once we refactor our DB structure?
- Removes manual progress increment when connecting data sources, since inventory progress is now automatically reloaded

Fix saving on add data screen

---

app/src/app/api/v0/city/[city]/inventory/[year]/progress/route.ts
app/src/app/api/v0/inventory/[inventory]/subcategory/[subcategory]/route.ts
app/src/models/index.ts

- Checkmarks now appear for manually completed subsectors
- Progress increments correctly
- Also disables SQL query logging in Sequelize
The issue was that the SubSectorValue was attached to a random SectorValue, not necessarily the right one for the current inventory.
This also fixes some data inconsistency issues resulting from that.

Fix manual data entry not increasing progress

---

app/scripts/catalogue-sync.ts

- Adds "<SOURCE NAME> by <PUBLISHER>. For more details see <SOURCE WEBSITE>." as the fallback for the `notes` field in `DataSource` when none is present. This way the scope this source is applied to has "completed" as the tag on it when manually editing it after connecting the source.
This is how the manual edit of third party data looks with this PR:

Add source references to data sources imported in catalogue-sync.ts

---

app/src/lib/store.ts

changes
- adds blacklist property to persistConfig in the redux store that blacklists api reducer from RTK service

fix(ui): blacklisted api reducer from being persisted

---

app/src/services/api.ts
k8s/cc-web-deploy.yml

Only set for the dev version for now

Add OPENCLIMATE_API_URL env var and use in API service

---

app/migrations/20240408115847-inventory-value-cascade.cjs

There were two foreign key constraints for both emissions_factor_id and inventory_value_id on the GasValue table. I've removed the one that didn't have `on update cascade on delete cascade` properties as this was making it impossible to delete an InventoryValue without manually deleting all of its GasValues first.

fix(db): not being able to disconnect source because of incorrect foreign key constraints

---

app/src/app/[lng]/onboarding/setup/page.tsx
app/src/app/api/v0/datasource/[inventoryId]/route.ts
app/src/util/helpers.ts

Still needs to be tested thoroughly

fix(api): population missing error for IEA source

---

global-api/requirements.txt
global-api/routes/city_boundaries_endpoint.py

Add `area` to the boundaries endpoint, so you can get the area when you fetch boundaries.
Also added a dedicated area endpoint, in case you want the area without all the extra data from the boundaries.
area is in km^2.

feat: add area to city boundaries and own endpoint

---

app/src/app/api/v0/city/[city]/file/[file]/download-file/route.ts
app/src/app/api/v0/city/[city]/file/[file]/route.ts
app/src/app/api/v0/city/[city]/file/route.ts
app/src/backend/UserService.ts
app/src/models/UserFile.ts
app/tests/api/userfile.test.ts

- allows admin accounts to find, create, delete user files for cities that they don't belong to
- allows admin accounts to edit/ delete inventory values for other accounts

feat(api): admin access control

---

app/src/util/series.ts
app/tests/series.test.ts

Added an estimate for series of annual values. Will either return the exact value, an extrapolation forward or backwards, or an interpolation.
If the extrapolation is too far (greater than the length of the series), it returns null.
Includes unit tests.

feat: function for estimating value from a series

---

global-api/migrations/versions/949c5b9cc18d_ef_in_country_code_table.py

this PR contains:
- new migration file that includes emission_factor_value and emission_factor_units columns in `country_code` table

fix:adding_missing_columns

---

app/src/app/[lng]/[inventory]/page.tsx
app/src/app/[lng]/page.tsx
app/src/util/check-user-session.ts

Changes
- Enables checks in the useSession() hook to redirect unauthenticated users to login for both the root page and dashboard

fix(ui): redirecting unauthenticated users to login page

---

app/scripts/catalogue-sync.ts

Fixes "For more details see undefined" in the data source description default messages

fix(script): usage of renamed parameter url in catalogue-sync.ts

---

app/migrations/20240506114511-inventory-v2.cjs
app/scripts/sequelize-auto.sh
app/src/app/api/v0/inventory/[inventory]/activity-value/[id]/route.ts
app/src/app/api/v0/inventory/[inventory]/activity-value/route.ts
app/src/app/api/v0/inventory/[inventory]/value/route.ts
app/src/app/api/v0/user/inventories/route.ts
app/src/models/ActivityValue.ts
app/src/models/GasValue.ts
app/src/models/SubSector.ts
app/src/models/User.ts
app/src/models/init-models.ts
app/src/util/validation.ts

Adds the `ActivityValue` table that is located on a new level between `InventoryValue` and `GasValue` now. This allows recording separate data for each activity inside of a SubSector + Scope (InventoryValue), so they can be tracked in compliance with the GPC.
Adds the following API routes:
- POST /api/v0/inventory/[inventoryId]/activity-value
- GET /api/v0/inventory/[inventoryId]/activity-value
- PATCH /api/v0/inventory/[inventoryId]/activity-value/[id]
- GET /api/v0/inventory/[inventoryId]/activity-value/[id]
- DELETE /api/v0/inventory/[inventoryId]/activity-value/[id]
The `id` parameter is `ActivityValue.id` in all of these cases.
Todo:

Inventory Backend v2 - Rise of the ActivityValue

---

global-api/importer/IPCC_2006/README.md
global-api/importer/IPCC_2006/clean_raw_data.py

This PR contains:
- readme file
- cleanning script 
for raw EF from IPCC 2006

Emission factors stationary energy scope1 - Global-API

---

app/README.md

I updated the README.md file with additional hints based on my experience when setting up the local dev environment on my system.

Updated the README.md file with additional hints

---

app/src/app/api/v0/chat/[inventory]/route.ts

bug fix: when a city had no population, using the Climate Advisor caused a 500 error. Added optional chaining operator "?" to fix this.
feature: Added minimal inventory context data to test if it is generally available. More will be added once the manual input 2.0 is working properly.

simple bug fix and tested access to inventory data

---

app/src/app/[lng]/[inventory]/data/[step]/page.tsx
app/src/app/api/v0/datasource/[inventoryId]/[sectorId]/route.ts
app/src/app/api/v0/datasource/[inventoryId]/route.ts
app/src/backend/DataSourceService.ts
app/src/i18n/locales/en/data.json

- Fixes the data source section on the add data page always showing "No sources found"
- Removes dependency on inventory progress data from data source search, so you can press the button before the remaining data has loaded (less wait times for users :sparkles:)
- Adds `removedSources` property to all data source routes to make debugging why a certain source was removed easier
- This potentially adds more data and filters by startYear/ endYear of the source in the backend instead of the database, so potentially more data needs to be scanned. In case this is too egregious, we can make it optional and add a "debugging mode" in the frontend. Good enough for now imo though.

Fix broken data sources section and add debugging tools for filtered out sources

---

.github/workflows/web-develop.yml
.github/workflows/web-tag.yml
.github/workflows/web-test.yml
k8s/cc-web-deploy.yml
k8s/test/cc-test-web-deploy.yml

Added a separate API Key to each of the three envs dev, test, prod to have more control and insights about usage.
Added a separate assistant ID to each of the three envs dev, test, prod to be able to change assistants in different systems without affecting the other systems.
Before merging, the new API KEYs have to be set in Github secrets!

Change env vars ca

---

app/scripts/catalogue-sync.ts

Use `SKIP_TIMESTAMP_CHECK` env var with value `"true"`
E.g. `SKIP_TIMESTAMP_CHECK=true npm run sync-catalogue`

feat(script): add ability to skip timestamp check for sync-catalogue script

---

app/src/app/api/v0/inventory/[inventory]/route.ts
app/tests/api/inventory.jest.ts

Added total emissions calculation to inventory GET endpoint and updated corresponding test.
- Modified the GET handler in `app/src/app/api/v0/inventory/[inventory]/route.ts` to calculate and include total emissions for an inventory.
- Updated the inventory test in `app/tests/api/inventory.jest.ts` to create activity values and verify the total emissions calculation.
1. Make a GET request to the inventory endpoint.
2. Verify that the response includes a `totalEmissions` field.
3. Run the updated test suite to ensure the new functionality works as expected.
This change provides a more comprehensive view of an inventory by including the total emissions calculated from all associated activity values. This information is valuable for users to quickly assess the overall environmental impact of …

bug: getTotalEmissions

---

app/src/app/[lng]/[inventory]/InventoryCalculationTab.tsx
app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsWidget.tsx
app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx
app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
app/src/util/types.d.ts

Since there was only one option ("by-activity") is on hold, I'm removing the selector.
before:
after:

remove selector since "by-activity" will not be implemented for now

---

app/migrations/20241001024448-inventory-total-country-emissions.cjs
app/src/app/[lng]/onboarding/setup/page.tsx
app/src/models/Inventory.ts
app/src/services/api.ts
app/src/util/validation.ts

This PR adds an attribute to inventories for total country emissions.
During onboarding, it also gets the value of the country emissions for the given year, and saves it with the inventory.

Gather total country emissions during onboarding and add to Inventory table

---

app/src/services/api.ts

When an activity is created/updated/deleted, invalidate the InventoryProgress and ReportResults tags

[ON-2523] Handle automatic update when a user enters Inventory Results

---

app/src/app/api/v0/inventory/[inventory]/results/[sectorName]/route.ts
app/src/app/api/v0/inventory/[inventory]/results/route.ts
app/src/backend/ResultsService.ts
app/src/util/form-schema/index.ts
app/tests/api/__snapshots__/results_sector.jest.ts.snap
app/tests/api/results.data.ts
app/tests/api/results.jest.ts
app/tests/api/results_sector.data.ts
app/tests/api/results_sector.jest.ts
app/tests/helpers.ts

currently we only  have the backend, can be tested by calling this url:
api/v0/inventory/:inventory-id/results/:sector-name-in-kebab-case/
returns data with this shape:
`{  
data: {  
activitiesForSectorBreakdown: {  
byActivity: {  
[buildingType: string]: {  
[fuelType: string]: {  
[unitType: string]: {  
activityValue: string;  
activityUnits: string;  
totalActivityEmissions: string;  
totalEmissionsPercentage: number;  
};  
};  
};  
};  
byScope: {  
[buildingType: string]: {  
[scopeNumber: string]: {  
[unitType: string]: {  
activityValue: string;  
activityUnits: string;  
totalActivityEmissions: string;  
totalEmissionsPercentage: number;  
};  
};  
};  
};  
};  
};  
}  `

[ON-2414] sector visualization backend (breakdown)

---

app/src/app/api/v0/assistants/threads/[inventory]/retrieve/route.ts
app/src/app/api/v0/assistants/threads/messages/route.ts
app/src/components/ChatBot/chat-bot.tsx

I moved the initialization of the thread (communication with openAI assistant API) from rendering the chat component to sending a message. 
Now the initial answer will take slightly longer, but we do not create a lot of empty threads each time it gets rendered.

On 2569 change initialize thread

---

app/src/app/[lng]/[inventory]/page.tsx

show the year on the population hover

[ON-2266] fix: hover population year

---

app/src/components/navigation-bar.tsx

Changes
- Adds logic to resolve and place the portuguese flag icon with brazilian flag for the dropdown
- Adds the same logic for the selected portuguese flag

fix(ui): replace portugal flag icon with brazil flag

---

app/src/app/api/v0/sector/[sectorId]/required-scopes/route.ts
app/src/components/Cards/SectorCard.tsx

because the db returns more scopes than those required by BASIC. We'll have to re-work the db when we start supporting more standards

bug: [ON-2663] go back to hardcoded scopes

---

app/src/backend/ActivityService.ts
app/src/backend/GPCService.ts

The error was caused because these sectors don't have a subcategories. Changed the logic to look for the subcategory and if not found, look for the subsector directly.

[ON-2892] fix: issue with loading IPPU and AFOLU

---

app/src/services/api.ts

Use the /api/v1/search/city endpoint for getting cities. This is faster, more accurate, and sorts the output by population (descending).
To test, go to the onboarding and search for a new city.

feat: use /api/v1/search/city in OpenClimate API

---

app/src/backend/ECRFDownloadService.ts
app/src/backend/InventoryProgressService.ts

Update the logic in `ECRFDownloadService.ts` and `InventoryProgressService.ts` to count inventory values as third party if a data source exists, removing the explicit check for source type as "third_party".
The change simplifies the condition by assuming any existing data source is third party, removing the need to check the specific source type. This streamlines the code and accommodates various scenarios where data could be categorized under different source types not strictly labeled as "third_party".

fix(api): count all InventoryValues with a source as third party

---

app/src/util/constants.ts

Restore scope 3 in the inventory types for `GPC_BASIC_PLUS` within the constants file.
The omission of scope 3 for `GPC_BASIC_PLUS` was identified as a regression issue needing rectification. This change reinstates the correct scope categories to align with the intended functionality and ensure comprehensive emissions tracking for `GPC_BASIC_PLUS`.

[ON-2853] restore scope 3 for basic+

---

app/migrations/20241211143647-cityInvite_delete_cascade.cjs

Implement cascading delete for the "CityInvite" table by updating the foreign key constraint to allow invites to be automatically deleted when a city is removed.
To ensure referential integrity and prevent orphaned records in the "CityInvite" table when a city is deleted, which resolves issues where invites remained without an associated city. This migration adjusts the foreign key constraint to cascade deletions, providing a cleaner and more automated maintenance process.

[ON-2881] fix deletion of cities with invites

---

app/migrations/20241210173228-gasvalue-activityvalue-on-delete-cascade.cjs

We have an error in the deletion of ActivityValue entries because of the foreign key to GasValue.
This migration adds an ON DELETE CASCADE and ON UPDATE CASCADE to the foreign key.
Add ON DELETE CASCADE action to the foreign key constraint on the `activity_value_id` column of the `GasValue` table in the database migration script.
These changes ensure that when a related record in the `ActivityValue` table is deleted, the corresponding entries in the `GasValue` table will automatically be removed, maintaining referential integrity and preventing orphaned records. This decision mitigates potential data inconsistencies and adheres to best practices in relational database management. …

fix: add ON DELETE CASCADE to foreign key of GasValue

---

app/src/i18n/locales/es/auth.json
app/src/i18n/locales/pt/auth.json

This fixes a problem with untranslated prompts in the password reset UI.
Add translations for password rule checks in Spanish and Portuguese localization files.
These changes ensure that users receive password rule instructions in their preferred language, enhancing user understanding and experience. This update addresses the missing translations for password complexity requirements which are crucial for guiding users during password creation or updates.

fix: translations for password rules; closes ON-3007

---

app/src/backend/InventoryProgressService.ts
app/src/backend/ResultsService.ts
app/src/models/InventoryValue.ts

Now that scope 3 has been added to basic+ this pr includes changes to accommodate that
Refactor the calculation of subcategory counts for sectors to accurately account for inventory types, and mark the `datasourceId` field in the `InventoryValue` model as deprecated.
The previous implementation of subcategory counting did not properly consider the specific scopes applicable to an inventory type, which could lead to incorrect sector percentages for GPC_BASIC_PLUS. The refactoring ensures that only applicable subcategories are counted based on inventory type, thus improving accuracy. Additionally, `datasourceId` has been moved to `ActivityValue`, and the field in the `InventoryValue` model is marked deprecated for eventual removal, reflecting data model changes for better organization.
> Is …

ON-3073 sector percentages fix for basic+

---

app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx
app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
app/src/backend/ResultsService.ts
app/src/util/types.ts

fixes the scope name from  PR https://github.com/Open-Earth-Foundation/CityCatalyst/pull/971
removes the "by activity" logic
fixes the bug where 3rd party data wasn't shown in the "by scope" view
Hide the breakdown by activity view in the inventory results section and adjust the logic to only display the breakdown by scope, along with restructuring the data processing methods to exclude activity data aggregation.
This change addresses task ON-3126, which requires hiding the breakdown view by activity to streamline the inventory output. The decision to focus only on scope-based data presentation is aimed at simplifying the data flow and ensuring efficient resource usage, especially as activity data handling has been found less critical. Restorability measures are indicated in the comments …

[ON-3126] hide breakdown by activity

---

app/src/backend/ActivityService.ts

If somebody else had added a data source to your inventory but you hadn't reloaded your page yet, this would lead to you being able to add another InventoryValue for the same GPC refno as the frontend state was inconsistent.
This PR prevents this in the backend by throwing an error if no inventoryValueId was passed but there is an existing value in the DB for the given GPC reference number.
Add validation to prevent the creation of duplicate InventoryValues based on the `gpcReferenceNumber` in `ActivityService.ts`.
This change addresses a bug (ON-3122) where multiple InventoryValues could be created with the same `gpcReferenceNumber`, leading to data inconsistencies. By checking for existing entries before creating a new InventoryValue, we ensure data integrity and prevent potential …

fix(api): ON-3122 prevent duplicate InventoryValues

---

app/src/backend/ActivityService.ts

Fix the conversion of the `amount` to a number before converting to BigInt in `ActivityService.ts` by using `toFixed(0)`.
The previous conversion method might have led to precision issues or conversion errors since `toNumber()` alone might not provide the desired integer format for BigInt conversion. Using `toFixed(0)` ensures the `amount` is properly formatted as an integer string before conversion, thus preventing potential runtime errors or incorrect values.

[ON-3137] fix bigint conversion

---

app/src/app/api/v0/emissions-factor/route.ts

The API route `/api/v0/emissions-factor` now returns an empty array instead of a 404 error when no emissions factors are found.
Remove the 404 error when no emissions factors are found and ensure the API returns a JSON response with an empty data set instead.
Previously, the API would return a 404 error if no emissions factors were found, which implied client error, though it is valid for some queries to yield no results. Returning an empty JSON makes the API more robust and offers an accurate representation of a search that yields no data, facilitating better client handling of such cases.

fix(api): don't return a 404 error when no emissions factors are found

---

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsWidget.tsx

The units we pull from OpenClimate for total country emissions are in tonnes, and we use kilograms in CityCatalyst. I updated the display code to correct it.
Correct the units difference between country total emissions and city total emissions by converting the country total emissions from tonnes to kilograms for accurate percentage calculation.
Previously, there was a unit mismatch where country emissions were in tonnes, and city emissions were in kilograms, causing incorrect percentage calculations. By multiplying the country emissions by 1000, both values are now in kilograms, ensuring accurate comparison and calculation.

fix: correct units difference between country and city total emissions

---

app/src/backend/ActivityService.ts

The request has either inventoryValueId or inventoryValueParams, never both. When  inventoryValueId was present, we got undefined on the gpcReferenceNumber and the funtion failed. We should only look for InventoryValue by gpcReferenceNumber if we don't already have the inventoryValueId
Add logic to check for existing inventory values by `gpcReferenceNumber` before saving multiple direct measures in `ActivityService.ts`, and throw a `BadRequest` error if a duplicate is found.
These changes prevent duplicate inventory values from being saved when the `gpcReferenceNumber` already exists in the database, which resolves a problem where multiple entries could inadvertently lead to data inconsistencies or errors during processing of direct measures. This approach ensures that each …

[ON-3144] fix save multiple direct measures

---

app/src/backend/ResultsService.ts

Fix the emissions breakdown by excluding inventory values where CO2eq is NULL.
An issue was identified where activities with a NULL CO2eq value were incorrectly being included in emissions breakdown results, leading to "cannot convert null to bigint". The condition `iv.co2eq IS NOT NULL` ensures only relevant data is considered in the calculations, thereby improving the accuracy of the emissions breakdown.

[ON-3037] fix emissions breakdown when there's an NA activity

---

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorTable.tsx
app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
app/src/backend/ActivityService.ts
app/src/components/HomePage/TabHeader.tsx

Fixes the following issues:
- 0 values were displayed as N/A
- Year over year percentages weren't displayed correctly
- ON-3144 Can't save a second ActivityValue for a given GPC refno
- % of emissions and based on previous year column always had the same values with different formatting
- missing padding below tab heading on dashboard
Refactor the `EmissionBySectorTable` to handle percentage changes and total inventory percentages appropriately, ensure previous year comparisons show "N/A" when applicable, and streamline the `ActivityService` logic for checking existing inventory values.
These changes address issue ON-3035 by ensuring that comparisons to previous year data result in displaying "N/A" when no previous data is available, thus preventing misleading zero values for percentage …

fix(ui, api): ON-3035 show based on previous year as N/A 

---

app/src/services/api.ts

When either data sources are connected/ disconnected or inventory values are changed or activity values are changed, update the following caches (tags) in Redux Toolkit:
- inventory total
- inventory progress
- inventory values
- report results
- yearly report results
Update cache invalidation tags in the API service to ensure proper refresh of inventory total and related data.
The cache invalidation mechanism needed consistency to ensure that updates to inventory and report data reflect immediately in the UI. This change addresses discrepancies in data shown by invalidating all relevant caches when certain mutations are performed.

fix(ui): properly update inventory total and other caches

---

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorTable.tsx
app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
app/src/app/api/v0/city/[city]/years/route.ts
app/src/components/InventorySelect.tsx
app/src/services/api.ts
app/src/util/types.ts

Add a new API route to query all available inventory years for a specified city and update related types and queries to accommodate this change across the codebase. 
These changes allow clients to specifically query for inventory year data related to a single city, improving data handling and efficiency over querying for data across all cities. The updates to types and queries ensure consistency and compatibility throughout the application, addressing the need for focused data retrieval and simplifying the InventorySelect logic.

fix(api): resolve access control issues on public dashboard

---

app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
app/src/util/helpers.ts

Fixes this error on the public dashboard (and probably normal dashboard too):
Although it occurs rarely because it depends on the order that the API requests resolve in and is fixed when the data is cached, so fixed by a reload.
Nicer to have it work immediately though :sweat_smile:
Add a check for empty `targetYears` object to prevent a crash when data isn't loaded yet on the public dashboard, and introduce a utility function `isEmptyObject` to aid in this validation.
The changes ensure that the application doesn't crash when `targetYears` data is absent by checking for an empty object before processing. This approach prevents potential null reference errors and adds robustness through code validation and error logging, thereby enhancing user experience on the public dashboard.
> Is this …

fix(ui): crash on public dashboard when targetYears wasn't loaded yet

---

app/src/app/[lng]/[inventory]/data/[step]/page.tsx
app/src/app/api/v0/datasource/[inventoryId]/datasource/[datasourceId]/route.ts
app/src/app/api/v0/inventory/[inventory]/value/[subcategory]/route.ts
app/src/components/Tabs/Activity/external-data-section.tsx
app/src/services/api.ts
app/tests/api/datasource.jest.ts
app/tests/api/inventory_value.jest.ts

Refactor the datasource deletion functionality to use `datasourceId` instead of `subCategoryId` throughout the application, including in API routes, services, and related tests.
The changes are made to improve accuracy and clarity when performing operations related to datasource deletion, as `datasourceId` offers a more precise identifier compared to `subCategoryId`. This update reduces potential confusion and aligns with the overall data management strategy in keeping identifiers consistent for data manipulation tasks. As a more accurate approach, it resolves associated errors and improves maintenance of the codebase.

[ON-3150] use datasource id to delete datasources, instead of subcategoryid

---

app/src/app/[lng]/[inventory]/data/[step]/SourceDrawer.tsx
app/src/i18n/locales/de/data.json
app/src/i18n/locales/en/data.json
app/src/i18n/locales/es/data.json
app/src/i18n/locales/pt/data.json

Fix the CO2 emission unit conversion in the SourceDrawer component by using a newly imported utility function `convertKgToTonnes` and remove unused localization keys for the number formatting.
The previous implementation incorrectly displayed emission totals in an unintended unit, leading to possible misunderstandings and reporting inaccuracies. By implementing `convertKgToTonnes`, we ensure consistent unit representation across the application. Additionally, the removal of the `intlNumber` translation keys cleans up unused code, aligning with best practices for code maintainability.

[ON-3157] fix wrong unit in 3rd party drawer

---

app/src/components/Modals/activity-modal/activity-modal-body.tsx

Default missing emission factors to 0 in the ActivityModalBody component.
To ensure that when emission factors for CO2, N2O, and CH4 are not provided or available, they default to 0 instead of an empty string, eliminating potential calculation errors and ensuring consistent data handling in emissions-related processes. This change addresses edge cases where missing values could lead to undefined behavior or runtime errors.

Default missing emission factors to 0

---

app/src/app/api/v0/inventory/[inventory]/value/[subcategory]/route.ts
app/src/app/api/v0/inventory/[inventory]/value/subsector/[subsector]/route.ts
app/src/services/api.ts

Introduce logic to delete existing related `ActivityValues` and set certain fields to `undefined` when `unavailableReason` or `unavailableExplanation` are provided, along with updating invalidation tags related to data marked as not occurring/unavailable in the API routes for inventory values.
This change handles cases where inventory data is not applicable by ensuring that both `unavailableReason` and `unavailableExplanation` must be provided together, otherwise throwing an error. Additionally, it cleans up data integrity by deleting associated `ActivityValues` and ensuring fields that are not applicable are set to `undefined`, while also updating caching tags to reflect these data deletions accurately. This approach maintains consistency and avoids partial data when the inventory value …

fix(api): delete existing data when refno not applicable

---

app/src/components/Modals/delete-inventory-modal.tsx
app/src/components/Tabs/my-inventories-tab.tsx
app/src/i18n/locales/de/settings.json
app/src/i18n/locales/en/settings.json
app/src/i18n/locales/es/settings.json
app/src/i18n/locales/pt/settings.json
app/src/services/api.ts
app/src/util/types.ts

Add functionality to delete an inventory through the DeleteInventoryModal component with password confirmation.
The feature update resolves the need for secure inventory deletion within the application by integrating API requests for password verification and deletion, and by providing user feedback upon successful or unsuccessful attempts. This enhances the user experience by ensuring necessary security protocols are followed and confirmations are communicated effectively.

[ON-2881] Fix delete inventory

---

app/src/services/api.ts

Invalidate the cache for "ReportResults" when disconnecting third-party data sources.
This change ensures that any cached report results are cleared and refreshed when a third-party data source is disconnected, preventing users from viewing stale data that may no longer be relevant or accurate.

[ON-3176] invalidate cache for report results when disconnecting 3rd party data

---

app/src/components/Modals/delete-inventory-modal.tsx

Changes
- Adds `FormControl `component to handle default form actions gracefully. In this case each time the enter/return key is pressed the form gets submitted and pushes the password query param shows up in the URL
Replace the default HTML `<form>` tag with a Chakra UI `<FormControl>` component in the `DeleteInventoryModal` component to prevent default form actions.
The default form behavior was unintentionally submitting or redirecting the page, causing disruptions in the user experience. Switching to `FormControl` aligns with the UI library's practices and prevents these actions, providing a more consistent and reliable modal behavior.

fix(ui): adds formcontrol to prevent default form action

---

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorChart.tsx
app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsForecast/EmissionsForecastChart.tsx
app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx
app/src/components/SegmentedProgress.tsx
app/src/lib/app-theme.ts
app/src/util/constants.ts

Change the logic of the charts to grab the color assigned to each sector. Once we have the colors list from Design, we can use those.
Unify color handling across the application by consolidating sector colors into a shared constant and updating components to use this new color schema.
These changes aim to maintain consistency in the color representation of sectors across different parts of the application, facilitating easier maintenance and updates to the color scheme. Centralizing color values in `allSectorColors` within the constants file reduces duplication and enhances readability.

[on-3141] unify colors 

---

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsForecast/EmissionsForecastChart.tsx
app/src/backend/OpenClimateService.ts

Enhance chart tooltips by adding growth rate information and consolidate color references by using a centralized color scheme.
The inclusion of growth rate data in the tooltips provides more detailed insights into emission trends over time, which is beneficial for data analysis and interpretation. Centralizing color references to use a unified `allSectorColors` array from constants ensures visual consistency across charts and simplifies color management.

[ON-3099] add growth rate to tooltip

---

app/src/components/password-input.tsx

Set a default input label for the password input to "Password".
This change ensures that the password input has a consistent and user-friendly label when none is provided, enhancing user experience by preventing potential issues with missing labels. The use of a default label improves accessibility and aligns with typical naming conventions.

fix: adds defaul input label for password input

---

app/src/backend/GlobalAPIService.ts
app/src/backend/ResultsService.ts
app/tests/api/emissions_forecast.jest.ts

Refactor `GlobalAPIService` to a class with a static method `fetchGrowthRates` and update related service and test files to utilize this new method for mocking in tests.
The changes address an existing issue where `jest` was unable to effectively mock the function `getGrowthRatesFromOC` due to its declaration nature. By refactoring the function into a static class method, we enable more robust mocking capabilities, resulting in more maintainable and reliable tests. Additionally, error handling was improved by adding a check for the existence of growth rates, which makes the service more resilient.

fix(test): mock methods not being called for GlobalAPIService

---

app/src/backend/CSVDownloadService.ts

- resolve issue with total emissions unit in generated csv file
Update the CSV report to display CO2 emissions in metric tons instead of kilograms.
The unit representation for CO2 emissions was incorrect in the CSV report, showing values in kilograms ("kg CO2e") instead of the standard metric tons ("t CO2e"), which is a more appropriate and industry-standard measure. This change helps to align the report with common scientific and environmental reporting practices.

fix: resolve units issue with csv report

---

app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx

Changes
- Adds isTruncated props to breadcrumb link this prevents text from overflowing into the second line
Add the `isTruncated` prop to the `BreadcrumbLink` component instances on the SubSectorPage.
These changes are implemented to ensure that the breadcrumb links accommodate longer text by truncating it to fit within the available space. This improvement enhances the user interface by preventing text overflow, thus maintaining a cleaner and more readable breadcrumb trail.

fix: adds istruncated prop to breadcrumb link

---

global-api/routes/ghgi_emission_forecast.py

Fix the SQL query to allow fetching emission forecasts for historical as well as future dates by comparing `future_year` to `forecast_year`.
The previous query condition restricted the results to only the specified `forecast_year`, which excluded data for years before this year. By changing the comparison to `future_year >= :forecast_year`, we ensure that we can retrieve forecasts for all years on or after the specified `forecast_year`, addressing the need for accessing historical data.

fix the query to allow for historical dates

---

global-api/importer/datasource_seeder/datasource_seeder.yaml

Add SNIS and SINIR data sources for retrieving national sanitation and solid waste management information by GPC reference number to the datasource_seeder.yaml file.
This change is being made to integrate the National Sanitation Information System (SNIS) and the National Solid Waste Management Report (SINIR) into the existing data retrieval framework. This allows for detailed insights and reporting on water supply, sewage services, and solid waste management emissions across municipalities in Brazil, using global protocol standards. These additions enrich the dataset with essential environmental data, aiding in better decision-making and reporting.

feat: adding snis and sinir information by gpcrefno

---

app/src/app/api/v0/inventory/[inventory]/results/route.ts
app/src/backend/ResultsService.ts
app/tests/api/results.jest.ts

Fix the handling of report results when the inventory has no data by ensuring that `totalEmissions` returns default values of an empty array for sectors and a "0" string for the total, and add test cases to verify this behavior.
This change addresses a bug where previous implementations failed to handle inventories without data gracefully, leading to potential errors or misleading responses. By providing default values, we ensure consistent and predictable API responses even when an inventory lacks data, thereby improving the robustness of the system. The addition of test cases ensures this behavior is validated and prevents future regression.

bug: [ON-3320] fix report results when inventory has no data

---

app/src/app/[lng]/user/invites/page.tsx

Fix the routing logic to navigate users to the home page (`/`) only when an invite is valid by adding a condition to check for errors before performing the routing.
The existing implementation incorrectly routed users to the home page even when an invite was invalid. This change ensures that users are only redirected to the home page when there is no error, maintaining the correct application flow and improving user experience. The commented-out code indicates the previously incorrect behavior was intentionally deactivated.

bug: [ON-3242] fix routing when invalid invite

---

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsForecast/EmissionsForecastChart.tsx

Adjust the legend formatting in `EmissionsForecastChart.tsx` by modifying the item width and updating the label for the 'ippu' series to use a shortened translation.
These changes improve the layout of the chart legend by making it more compact, which enhances visual clarity and ensures labels fit better in the allocated space. Additionally, using a shorter label for the 'ippu' series aids in better readability and alignment with design standards.

[ON-3325] legend formatting

---

app/src/components/HomePage/HomePage.tsx

since we don't re-render the PrivatePage component when the language is changed, using the language from cookies to pass the correct language around.
Update language selection logic to prioritize the value from cookies over the URL parameter for rendering the HomePage component in both private and public views.
The change ensures a more consistent user experience by using the user-preferred language setting stored in cookies (`i18next`) over the language provided in the URL. This addresses a previously identified issue where the language setting might differ from user preference due to URL language parameter discrepancies.

[ON-3266] Fix language in Emissions Forecast

---

global-api/routes/ghgi_emissions.py

Refactor the database query in `ghgi_emissions.py` to adopt a common table expression that aggregates emissions data, adjust the response structure to include aggregated gas information, and update the data parsing logic to match the new structure.
The current emissions data response structure lacked aggregation of gas information, which can lead to redundant data processing and complexity. The refactoring improves data organization and efficiency by using a common table expression to encapsulate emission-to-gas mappings as `gas_info`, simplifying data handling in subsequent application logic.

fix updated global-api activity data response structure

---

app/src/i18n/locales/de/settings.json
app/src/i18n/locales/en/settings.json
app/src/i18n/locales/es/settings.json
app/src/i18n/locales/pt/settings.json

Changes
- Adds translations for email address placeholder
Add translations for the email placeholder in German, English, Spanish, and Portuguese localization files.
To ensure users have a consistent experience across different languages by providing a translated placeholder for email input fields, which previously lacked this translation. This update improves the internationalization support of the application by covering missing translations in the settings configurations.

fix: adds translation for email

---

app/src/components/ChatBot/chat-popover.tsx

Changes
- Adds max-w prop to button prevents its from stretching across the screen
- Uncomments Button Icon
Add a maximum width restriction to the "Ask AI" button and uncomment the associated icon.
The maximum width is introduced to ensure consistent display and avoid text overflow issues, while uncommenting the icon reinstates intended visual elements that were previously disabled for potentially debugging purposes. This approach enhances both the functionality and appearance of the chat popover component.

fix: adds max-w to ask ai, uncomments icon

---

app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx

Changed
- Resolves default tab not showing by using refNo from subsectors instead
Update the logic to set the default reference number on the AFOLU and IPPU tabs by utilizing the `subSectorData.referenceNumber` instead of the first scope's reference number.
The previous implementation did not correctly set the default reference number when the tabs were loaded, which could lead to incorrect data being displayed. By directly using `subSectorData.referenceNumber`, the default settings are accurately initialized, enhancing user experience by ensuring correct and expected data display.

fix: afolu and ippu tabs not default tab not being set

---

app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx
app/src/components/Tabs/Activity/activity-tab.tsx

Also simplify default tab handling by not using full reference numbers as tab values
Refactor the subsector page to set the first scope tab as the default selection and update the `Tabs.Content` component positioning within the subsector page and activity tab components.
The changes address an issue where the first scope tab was not being selected by default on the subsector page by initializing `Tabs.Root` with a "0" default value. The refactor improves the tab navigation and ensures consistency by standardizing the use of index-based values for tab selection rather than relying on reference numbers, thus providing a more robust and maintainable structure for handling tabs across different components. …

fix: first scope tab not selected by default on subsector page

---

app/src/app/[lng]/auth/login/page.tsx

Fixes 404 error after login when navigating directly to login page
Modify the login page to prevent redirection to the invites page if query parameters lack a token.
Previously, users could be redirected to the invites page even when query parameters didn't include a token, causing unnecessary navigational logic that could be confusing. This change ensures redirection only occurs when a token is present, improving navigation accuracy.

fix(ui): don't redirect to invites page without a token in query params

---

app/src/backend/PopulationService.ts

Fix the `PopulationService` to correctly return `countryPopulation` and `regionPopulation` values.
The changes ensure that the service returns the correct population attributes for country and region by referencing the correct property names (`countryPopulation` and `regionPopulation`) in the returned object. This corrects an error where incorrect data was previously being accessed and displayed, ensuring accurate data representation.

bug: Fix population service to return city & region values

---

app/src/backend/ResultsService.ts

Modify the CO2 equivalent (co2eq) summation logic to handle potential null values by using a default value of 0 in `prepareEmissionsData` function.
The change ensures robustness by preventing potential runtime errors when `co2eq` is null due to scopes not being applicable, thereby maintaining consistent function behavior and accurate emission calculations. This is crucial to ensure the service handles all data scenarios gracefully without requiring upstream data modification.

[ON-3478] handle null co2eq for cases when scope is not applicable

---

app/src/app/[lng]/[inventory]/data/[step]/SourceDrawer.tsx

Fix the misalignment between subcategory totals and total emissions by correcting the conversion logic from kilograms to tonnes and ensuring accuracy in computation.
The previous implementation led to discrepancies in displayed emissions due to incorrect conversion, resulting in a bug that misrepresented total emissions. This change addresses the source of the misalignment by correctly applying the conversion factor and utilizing type-casting to handle numerical precision, ensuring consistency across category calculations.

bug: [ON-3484] fix Misalignment between the totals in subcategory and total emissions

---

app/src/app/[lng]/[inventory]/data/[step]/SourceDrawer.tsx
app/src/app/[lng]/[inventory]/data/[step]/[subsector]/ScalingSection.tsx
app/src/i18n/locales/en/data.json

Refactor the scaling methodology display logic in SourceDrawer to be encapsulated within a new ScalingSection component that is only rendered when necessary, and update localization data to include "region-population".
This change addresses a bug by ensuring that the scaling methodology is shown only when applicable, enhancing code maintainability by isolating this logic into a separate component. Additionally, the inclusion of "region-population" in localization supports the expanded conditional logic needed for accurate data representation, aligning the display more closely with the source data's spatial resolution.

bug: [ON-3481] show scaling methodology only when it's needed

---

app/src/components/custom-selectable-buttons.tsx
app/src/components/steps/add-inventory-details-step.tsx

Changes
- fixes button layout and styling
- adds selectable button component
Replace radio buttons with a custom selectable button component to improve layout and styling in the inventory details step.
The changes are being made to enhance user experience by using more visually engaging button components instead of traditional radio buttons, improving both layout and user interaction within the inventory details step. The implementation of the `CustomSelectableButton` component allows better customization and appeal by dynamically styling buttons based on selection state.

fix: radio button layout and styling

---

app/src/app/[lng]/[inventory]/data/[step]/SourceDrawer.tsx
app/src/app/[lng]/[inventory]/data/[step]/SourceDrawerActivityTable.tsx
app/src/i18n/locales/en/dashboard.json

Refactor `getTotalEmissions` to correctly accept an activity as a parameter and update translation strings to include "error-fetching-sector-breakdown".
The calculation of total emissions was incorrect due to a missing parameter in the `getTotalEmissions` function call; this has been fixed to improve accuracy by passing the correct `activity` object. Additionally, a new translation string has been added to handle error messaging for sector breakdown fetching, enhancing the application's internationalization support.

Bug: [on 3484] fix total emissions included

---

app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx

Fix the conditional logic to display an error toast and log an error message when an error is present during sector breakdown fetching.
The previous implementation incorrectly skipped showing the error toast when an error occurred due to a logical inversion. This fix corrects the logic to improve error handling and debugging by ensuring users are notified of errors and relevant messages are logged.

bug(ui): show error toast when error is present

---

app/src/components/Modals/delete-activity-modal.tsx
app/src/components/Tabs/Activity/emission-data-section.tsx

Fixes being unable to click the delete activity button in the modal on the subsector data page.
Update `selectedActivityValue` to handle undefined states by adjusting its type and adding a validation check when an activity is being deleted.
These changes are necessary to prevent errors caused by undefined `selectedActivityValue` when attempting to delete an activity. By ensuring `selectedActivityValue` can be undefined and checking its presence, we improve the robustness of the activity deletion feature, preventing runtime errors and providing a better user experience.

fix(ui): ON-3492 unable to delete activities in manual input

---

app/e2e/helpers.ts
app/e2e/login.spec.ts

Ensure the user is logged out before performing the invalid data test in `login.spec.ts` by navigating to the signout endpoint prior to the test execution.
Logging out before the test ensures the test environment is in a consistent and known state, preventing potential order of execution issues that might arise if the user is already logged in. This change helps to maintain the reliability and accuracy of end-to-end tests by avoiding false positives or negatives due to session-related issues.

fix(e2e): log out before performing invalid data test in login.spec.ts

---

app/src/components/percentage-breakdown-input.tsx

Add `overflow-scroll` class to the `PopoverContent` in the `percentage-breakdown-input.tsx` component to fix the shifting glitch.
The change addresses a UX bug where the component content shifts unexpectedly due to overflow issues; adding the `overflow-scroll` class ensures consistent rendering without disrupting the layout, resolving user-reported issues effectively.

feat(gtm):[on-3456] fixes the shifting glitch of the percentage-breakdown component

---

app/src/components/HomePage/Hero.tsx
app/src/i18n/locales/en/dashboard.json

Fetch the city population data source (well, *probable* data source... we match by population value and year) and show it in the tooltip popup in the Hero.
I considered a lot of different options, like saving the population data source in the inventory at onboarding time, but since we only use it in this single place, I opted to just do another API call to get it.
It would be cool to only do the API call in the unlikely event that someone hovers the tooltip, but I can't find an easy way to do this. So, we're paying an extra API hit on the dashboard.
Fetch the population data source using `useGetOCCityDataQuery` and display it in the tooltip on the homepage.
These changes enhance the user interface by providing more context for the population data displayed on the homepage. By fetching the …

feat: fetch the population source and show it in the tooltip

---

app/src/app/api/v0/admin/connect-sources/route.ts
app/src/backend/AdminService.ts
app/src/backend/DataSourceService.ts
app/tests/api/admin.jest.ts

Independent of bulk inventory creation
Create a separate `connect-sources` endpoint in the API, which allows for bulk connection of data sources based on specified city locodes and years, independent of inventory creation.
This change provides a distinct endpoint that caters to specific administrative needs by connecting data sources without tying them directly to the inventory creation process, improving modularity and ease of management. It also ensures that only users with admin roles can perform these operations, maintaining control and security.

feat(api): ON-3610 create separate connect-sources endpoint

---

app/src/components/dropdown-select-input.tsx

Refactor the `DropdownSelectInput` component to eliminate duplicate options by directly toggling selected items and consolidating the handling of subsector name selections within a `Box` component.
These changes prevent duplication of selected options and simplify the logic flow by removing the separate `handleCheckboxChange` function, which was partially redundant. By directly toggling selections, we make the code cleaner and improve maintainability, addressing the issue of duplicate dropdown options.

bug(ui): ON-3564 Fix duplicate Dropdown options

---

app/src/components/percentage-breakdown-input.tsx

Disable portalling on the `PopoverContent` of the percentage breakdown component.
Portalling was causing rendering issues in certain layouts, which disrupted user interaction with the component. Disabling it ensures a more consistent and reliable user experience without unintended layout shifts.

Bug: disable portalling on percentage breakdown component 

---

app/jest.config.ts
app/tests/api/organization_invite.jest.ts
app/tests/tsconfig.json

The tests are passing locally but still getting error on the CI:
Implement organization invitation feature with new database migration, TypeScript models, API routes, and email invitation template along with associated tests.
The changes are intended to extend the functionality of the application by enabling administrators to send and manage invitations to users for joining an organization. This required creating appropriate data models, API endpoints to handle invite creation and retrieval, and an email template to notify invitees, enhancing overall organizational management in the application. The existing "CityInviteStatus" was consolidated to "InviteStatus" to maintain consistency and reuse across different invitation use cases.
> Is this description stale? Ask me to generate a new …

Nina/feat/on 3549/invite collaborator tests

---

app/src/components/ui/accordion.tsx

And make it the default
Implement a "center" `indicatorPlacement` mode for the `AccordionItemTrigger` component in the accordion UI.
This change provides a new positioning option for the accordion indicator, offering more flexibility in UI customization as requested in feature ON-3575. By default, the indicator is now centrally aligned unless specified otherwise, which addresses the requirement for a enhanced visual design.

feat(ui): ON-3575 implement center indicatorPlacement mode for accordion

---

app/scripts/create-admin.ts
app/src/backend/AdminService.ts

Improve error feedback in `AdminService.ensureIsAdmin` to provide more context when authorization checks fail, and update the `createAdmin` script to use "admin" as the role name.
Previously, the error message for users failing the admin check was generic, potentially leading to confusion; the updated message includes the user's current role for clarity. Additionally, changing "Admin" to "admin" in the `createAdmin` function standardizes the role naming convention, likely to maintain consistency with other parts of the system.

fix(api): add better error feedback for AdminService.ensureIsAdmin

---

app/src/app/api/v0/check/health/route.ts
app/src/app/api/v0/check/liveness/route.ts

This adds two probe API endpoints for the Web app to help with k8s deployment (see https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/ ):
- /api/v0/check/liveness/ simply checks if the server is up and returns some constant data
- /api/v0/check/health/ checks if the server is able to operate. Right now, it checks if it can run a simple database query.
Once these are in the app, I will add them to the Kubernetes deployment.
Add health and liveness endpoints for Kubernetes in the API to check application status and version.
These changes provide necessary endpoints for Kubernetes to monitor the application's health and liveness, facilitating improved deployment management and enabling automatic health checks. The approach ensures that the application can …

feat: wellness endpoints for k8s

---

global-api/routes/ghgi_emissions.py

Add the `emissionfactor_datasource` field to the emissions factor data retrieval in the `db_query` method within the `ghgi_emissions.py` route.
This change is made to ensure that the data source of the emission factors is explicitly included in query results, enhancing data transparency and allowing consumers of the API to trace the origin of emission factor values. It aligns with the requirement for clearer data provenance in emissions reporting.

fix added the datasource for emissions factor in route

---

app/src/app/[lng]/[inventory]/data/manage-sectors/NotationsDefinitionAccordion.tsx
app/src/app/[lng]/[inventory]/data/manage-sectors/SectorTabs.tsx

Changes
- Adds flex props to align text correctly
- Adds line-clamp and max-w to sector tab text
Adjust the styling of the NotationsDefinitionAccordion and SectorTabs components by adding flex properties to align text properly and setting a maximum width for tab triggers to improve text display.
These changes address visual bugs related to text alignment and truncation within the NotationsDefinitionAccordion and SectorTabs components, enhancing user interface consistency by ensuring the text is properly aligned and does not overflow, providing a clearer UI experience.

Fix: on 3635 notation key manager bugs

---

app/src/components/navigation-bar.tsx

Changes
- Adds condition to render admin menu item
Add a condition to render the admin menu item based on the user's role in the navigation bar component.
Without this condition, the admin menu item is rendered for all users indiscriminately. This change ensures that only users with an admin role will see the admin menu item, enhancing both security and user experience by preventing unauthorized access to admin features.

fix: adds condition to render admin menu item

---

app/src/app/[lng]/[inventory]/data/manage-sectors/SectorTabs.tsx
app/src/app/[lng]/[inventory]/data/manage-sectors/page.tsx

Add an error toast notification when saving notation keys fails in the `SectorTabs` component.
This change provides immediate user feedback when an error occurs during the save operation, enhancing the user experience by clearly indicating when the action was unsuccessful. Prior to this, the error was only logged to the console without a visual indication to the user.

feat(ui): show error toast when saving notation keys fails

---

app/src/app/[lng]/[inventory]/data/manage-sectors/NotationsDefinitionAccordion.tsx
app/src/app/[lng]/[inventory]/data/manage-sectors/SectorTabs.tsx
app/src/app/api/v0/inventory/[inventory]/notation-keys/route.ts

Shows existing unavailable reason/ explanation (which allows editing/ updating).
Don't clear inputs on save (to allow further editing).
Hides extra arrow on accordion.
Hides unnecessary sectors in tabs (directly from API response)
Load existing data into the notation key manager by modifying the SectorTabs component to update state with existing data and filtering applicable sectors based on inventory type in the API route.
These changes are intended to enhance the user interface by pre-populating fields with existing notation data, improving usability, and ensuring the accuracy of displayed sectors based on inventory types. The adjustments streamline the workflow by reducing redundant input actions for the user and align the visible data with the system's inventory specifications.
> Is …

fix(ui): load existing data into notation key manager

---

global-api/routes/ghgi_emissions.py

Round emissions values and their calculations to the nearest whole number in the global API's emissions queries.
Rounding emissions values improves data readability and reporting accuracy by presenting figures in a simpler, more digestible format. This enhances user experience and aligns with common data presentation standards when precise decimal details are unnecessary.

fix: emissions from global api rounded

---

app/src/app/[lng]/[inventory]/data/[step]/page.tsx
app/src/components/HomePage/InventoryCalculationTab.tsx
app/src/util/helpers.ts

On dashboard and add data (sector) pages
Clamp inventory progress calculations between 0 and 100% using a new utility function `clamp` to ensure progress values remain within the valid range.
This change addresses issues where inventory progress values could exceed the intended limits, causing incorrect UI behavior by clamping these values to a normalized range between 0 and 100%. Implementing a utility function ensures consistency and reusability across different parts of the codebase.

fix(ui): clamp inventory progress between 0 and 100%

---

global-api/routes/get_climate_actions.py

Remove erroneous comma after "Biome" and add an ORDER BY clause for "ActionID" in the SQL query within `get_climate_actions.py`.
The removal of the comma resolves a syntax error, ensuring the query executes correctly. The addition of the ORDER BY clause ensures that results are consistently ordered by "ActionID", which is critical for predictable data handling and presentation in the application.

fix: removed comma after biome and added order by

---

app/src/app/[lng]/[inventory]/settings/page.tsx

Changes
- Changes default bg color for tablists to white (backgroundLight)
Change the background color of the `Tabs.List` component from the default gray to white in the settings page.
The default gray background color was not consistent with the design guidelines, which required a white background to improve visual clarity and consistency across the application's user interface. This change ensures that the settings page aligns with the specified design standards.

fix: ON-3570 changes background color from default gray to white

---

app/src/app/api/v0/admin/bulk/route.ts
app/src/app/api/v0/admin/update-inventories/route.ts
app/src/backend/AdminService.ts
app/tests/api/admin.jest.ts

In bulk inventory creation and bulk inventory update API endpoints
Add the ability to define and update the project ID associated with city inventories through new fields in bulk create and update operations.
Currently, associating a project ID with city inventories is not supported, limiting our ability to organize and manage inventories by projects. By introducing this feature, users can better manage inventories within their respective projects, enhancing functionality and alignment with user requirements.

feat(api): allow defining and updating project ID of cities

---

app/src/backend/AdminService.ts

When calling the connect-sources API endpoint to fix prioritization of data sources
Refactor data source grouping logic to organize by GPC reference number instead of subsector in the AdminService.
The change ensures that data sources are grouped more appropriately by their GPC reference numbers, which may provide a more effective and relevant criterion for prioritization, given more consistent reference attributes in source categories and sectors. This enhances the efficiency and accuracy of data retrieval processes.

fix(api): ON-3758 group data sources by GPC refno

---

app/src/components/Cards/SectorCard.tsx

Clamp the dashboard subsector progress values to a maximum of 100% in the `SectorCard` component and update the handling of optional `sectorProgress` values.
Progress can exceed 100% due to calculation errors, leading to inaccurate UI representation; the clamping ensures that displayed progress values remain logical and capped at 100%. Additionally, handling `sectorProgress` as an optional value improves robustness against undefined data inputs and prevents potential runtime errors.

fix(ui): ON-3698 clamp dashboard subsector progress to max 100%

---

app/src/components/HomePage/TabHeader.tsx

Changes
- Adds condition using isPublic variable to hide manage subsectors button on public dashboard
Add a condition to render the "manage subsectors" button only when `isPublic` is `false`.
The button should be visible only to certain users, presumably those with permission to manage subsectors, ensuring it doesn't appear in public views. This change enhances security and user experience by displaying relevant options based on user access levels.

adds condition to render manage subsectors sector button

---

.github/workflows/web-develop.yml
.github/workflows/web-tag.yml
.github/workflows/web-test.yml

Add new S3 bucket credentials `AWS_FILE_UPLOAD_S3_BUCKET_ID` and `AWS_FILE_UPLOAD_REGION` to GitHub workflows `web-develop.yml` and `web-tag.yml`.
These changes are being made to facilitate file uploads to the designated S3 bucket (`citycatalyst-files`) in the specified AWS region (us-east-1). This inclusion is necessary to ensure the workflows have the required S3 configuration and credentials, thereby enabling seamless integration with AWS for file handling tasks.

chore: include new s3 credentials in workflow

---

app/migrations/20250512093848-update-unavailable-reason.cjs
app/src/app/[lng]/[inventory]/data/[step]/types.ts
app/src/app/[lng]/[inventory]/data/manage-sectors/SectorTabs.tsx
app/src/app/api/v0/inventory/[inventory]/download/route.ts
app/src/app/api/v0/inventory/[inventory]/notation-keys/route.ts
app/src/i18n/locales/de/data.json
app/src/i18n/locales/de/manage-subsectors.json
app/src/i18n/locales/en/data.json
app/src/i18n/locales/en/manage-subsectors.json
app/src/i18n/locales/es/data.json
app/src/i18n/locales/es/manage-subsectors.json
app/src/i18n/locales/pt/data.json
app/src/i18n/locales/pt/manage-subsectors.json

Changes
- Replaces notation key value presented elsewhere with included elsewhere
- Updates translation keys and strings
- Updates subcategory type key value
- Updates CIRIS file download route mapping key
- Updates notation-key manager route
- Adds migration to update all occurences
- Removes presented elsewhere translations
Replace all occurrences of "presented-elsewhere" with "included-elsewhere" across the codebase and update related internationalization files and UI components accordingly.
This change is being made to standardize the terminology across the application, ensuring consistency in the user interface and underlying data structures. The new term "included-elsewhere" better reflects the intended meaning related to emissions data handling, offering clearer communication to …

feat(ui/api): ON-3844 repalaces presented-elsewhere with included-elsewhere

---

app/src/app/[lng]/[inventory]/layout.tsx

Add a fallback theme for anonymous users when no theme is loaded in the public dashboard.
Without these changes, anonymous users may experience broken styling since no theme would be applied, negatively affecting their user experience. The fallback to "blue_theme" ensures consistency and visual integrity for all users, addressing the issue tracked in ON-3928.

bug(theming): [ON-3928] no theme loads for anonymous user in public dash

---

app/src/components/Modals/activity-modal/activity-modal-body.tsx

Modify the emissions factor inputs to be correctly enabled or disabled based on the emissions factor type input selection within the `ActivityModalBody` component of the user interface.
Previously, the emissions factor inputs did not correctly reflect the enabled/disabled state when the emissions factor type was "custom", leading to potential user confusion. This change ensures that these inputs are disabled when the type is "custom", aligning with the intended user experience and UI logic. Additionally, some minor refactoring was done for variable naming consistency and readability.

fix(ui): ON-3906 incorrect emissions factor inputs enable/ disabled state

---

app/src/components/HomePage/Hero.tsx
app/src/components/HomePage/ProjectDrawer.tsx
app/src/i18n/locales/de/dashboard.json
app/src/i18n/locales/en/dashboard.json
app/src/i18n/locales/es/dashboard.json
app/src/i18n/locales/pt/dashboard.json

Changes
- Adds logic to render default project instead of `cc_project_default` on dashboard and drawer
- Adds translations for other languages
Add logic to render a default project name in the UI and update translations to include a new key for "default-project" in multiple languages.
These changes address the need to properly display a default project name in the UI when a specific condition is met and to ensure translation consistency across supported languages so that users experience a localized interface. This approach aids in improving user experience by providing clarity and ensuring that the application UI accommodates multiple languages effectively.

fix(ui):ON-3866 adds logic to render default project and adds translations

---

.github/workflows/web-tag.yml

Use different environment variables for AWS S3 upload configuration in the production environment within the GitHub CI/CD workflow.
This change ensures that production deployments utilize the correct secure credentials and specific S3 bucket identifiers distinct from those used in other environments, enhancing security and aligning with best practices for handling sensitive production data. The update provides a clear separation of environment-specific configurations and reduces the risk of mishandling production data with non-production credentials.

feat(ci): use different env vars for S3 upload in prod

---

app/src/backend/ManualnputValidationService.ts

For different activity types/ sub-categories
So it allows saving two activities for e.g. II.1.1 that both have transport type all if they have different activity types (e.g. different fuel types etc.).
Enhance `ManualInputValidationService` to support saving multiple different activities by incorporating an exclusive field and ensuring constraint validation is activity type-specific.
The modification addresses the need to differentiate between activities of various types that might have conflicting exclusive fields, preventing errors during data entry. By adding an `activityTypeField`, validation now accounts for activity sub-categories, correctly allowing parallel entries while ensuring exclusivity within the same type, thereby resolving an existing issue where conflicting activity …

fix(api): ON-3925 allow saving multiple different activities with exclusive field

---

app/package-lock.json

We've had this issue for a while, every time we run npm i, it adds the swc to the package-lock.json
Enhance the InventoryResultTab component by adding a feature to view data sources in a drawer interface and update the DataSourceService API to fetch and handle these sources more efficiently, including scaling data for inventories, while ensuring all necessary dependencies are declared in `package-lock.json`. 
The improvement allows for more detailed data source tracking and analysis within the application, enhancing the user experience by providing quick access to source details directly from the table interface. The updated API endpoints and services ensure accurate and scalable data handling, which aligns with the overall goal of improving data management and user interaction within the …

chore: add missing swc dep from package-lock.json

---

app/src/app/[lng]/[inventory]/data/manage-sectors/SectorTabs.tsx

Changes
- Adds shadow to enhence the select dropdown visbility
Add a shadow to the notation key dropdown in SectorTabs component.
This change enhances the UI by providing a subtle shadow effect which improves the dropdown's visual prominence and accessibility within the application, addressing user feedback on styling improvements.

fix: adds shadow to notation key dropdown

---

global-api/migrations/versions/83dae560c337_formular_values.py

Add a migration to introduce four new tables (`gpc_sector`, `publisher_datasource`, `ghgi_methodology`, and `formula_input`) in the database to support storing formula values and related metadata.
These changes are necessary to support the storage and management of formula inputs and values, which are critical for the application's functionality related to greenhouse gas inventories. The approach involves creating dedicated tables with appropriate relationships and constraints to ensure data integrity and consistency. The migration is designed to integrate seamlessly with the existing database schema.

feat: added the table needed for adding formula values to the database

---

app/src/backend/ECRFDownloadService.ts

Import `fs` and `path` modules to check for the existence of the template file path and handle errors accordingly in the `ECRFDownloadService`.
Previously, there was a failure to read the template file on the development environment due to incorrect file path handling. By using the `path` module to generate an absolute path and the `fs` module to check for the file's existence, this fix ensures better error handling and resolves the path issue, thus avoiding runtime errors when the file is not found.

fix: fixes failure to read template file error on dev

---

app/Dockerfile

Include the `templates` folder in the production Docker image by adding a copy command in the Dockerfile.
The change ensures that the necessary template files are available in the production environment, allowing ECRF download functionality to work as expected. The omission of the templates directory led to issues in production, and this approach aligns the Docker configuration with development setups where templates are present.

fix: include templates folder in production image for ECRF download

---

app/src/backend/ResultsService.ts

Remove the unused LEFT JOIN on "ActivityValue" in the fetchInventoryValuesBySector query.
The join on "ActivityValue" was not contributing to the query's output and could lead to unnecessary complexity and potential performance issues. Removing it simplifies the query and ensures optimal execution without altering the intended data retrieval.

fix(api): remove unused join on ActivityValue for fetchInventoryValuesBySector

---

app/src/app/api/v0/projects/[project]/users/route.ts
app/src/services/api.ts

URL searchParams.get() automatically converts + to spaces, breaking emails
like cephas+1@openearth.org. This fix restores + characters after decoding.
Modify the handling of email query parameters in URL to preserve + characters by replacing spaces with +.
In the current implementation, '+' characters in email addresses are incorrectly converted to spaces due to standard URL decoding behavior. This change ensures that the email addresses are correctly interpreted by manually replacing spaces back to '+', thus preserving the original email format as intended.

fix(api): handle + characters in email URLs to prevent space conversion

---

app/src/app/[lng]/organization/[id]/account-settings/team/index.tsx

Remove the `flex` property from the `Box` component within the TeamSettings component.
This change addresses a CSS issue in the Teams accordion feature where the `flex` property was not necessary, ensuring the layout aligns correctly without unintended overflow behavior. The previous implementation occasionally caused unwanted layout distortion in certain browsers.

fix: css fix for teams accordion

---

app/migrations/20250625163028-duplicate-inventory-values.cjs

Create a database migration script to remove duplicate inventory values for the same GPC reference number and add a unique constraint to prevent such duplicates in the future.
These changes address the issue of duplicate entries in the "InventoryValue" table, which could lead to incorrect inventory reporting. By merging duplicate entries, ensuring associated "ActivityValue" records are updated, and enforcing a unique constraint, the integrity and accuracy of the inventory data are maintained.

fix(db): create migration to remove duplicate inventory values for the same GPC refno

---

app/src/app/api/v0/emissions-factor/route.ts

Remove the incorrect alias for the `EmissionsFactor` table in the ranking query within `route.ts`.
The wrong alias was causing an issue by not correctly matching column names during query execution, leading to errors in data retrieval. This change corrects the alias usage to prevent query mismatches and ensure the desired data is accurately ranked and retrieved.

fix(ui): ON-4174 remove wrong alias for EmissionsFactor table in ranking query

---

app/src/app/[lng]/[inventory]/data/manage-sectors/SectorTabs.tsx

changes
- changes toast type from info to success
Update the toast notification type from "info" to "success" in the `SectorTabs` component.
The toast notification's nature was incorrectly represented as "info," which did not accurately reflect the successful outcome of the action taken. Changing the type to "success" provides a more appropriate and clear feedback to the users indicating that the quick action was applied successfully.

fix: adds correct toast type

---

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsForecast/EmissionsForecastCard.tsx
app/src/app/[lng]/auth/signup/page.tsx
app/src/components/HomePage/DownloadAndShareModals/DownloadButtons.tsx
app/src/components/email-input.tsx
app/src/components/password-input.tsx
app/src/i18n/locales/de/dashboard.json
app/src/i18n/locales/en/dashboard.json
app/src/i18n/locales/es/dashboard.json
app/src/i18n/locales/fr/dashboard.json
app/src/i18n/locales/pt/dashboard.json

Revise the title for the emissions forecast in the `EmissionsForecastCard` component, update translation strings for the breakdown of sub-sector emissions across multiple languages, and comment out unavailable download format options in `DownloadButtons`.
The changes are being made to correct the text for emissions breakdown titles to provide clarity and consistency across different languages, and to prevent users from seeing and attempting to select download formats (CIRIS and PDF) that are currently unavailable, thus improving the user experience.

on-4108/hide unavailable download formats | on-4107, bugfixes

---

app/seeders/20231114094254-emissions-factors.cjs

Comment out "ghgprotocol" from the seed data folders array in `20231114094254-emissions-factors.cjs`.
The "ghgprotocol" data is not required for the emissions factors seed process, leading to erroneous or redundant data loading. This change streamlines the seed data to include only necessary data sources and prevent future confusion or errors.

fix: remove ghg from ef seed data

---

app/src/backend/UnitConversionService.ts
app/src/backend/formulas.ts

we were rounding very small numbers (10^-5) to 1, messing up the calculation
Correct the CO2Eq calculation by fixing a typo in the fuel type key and removing the rounding logic in the emissions calculation.
The typo in the fuel type key prevented the system from accurately identifying fuel data, potentially causing errors or inaccuracies in emissions calculations. The removal of the rounding logic aims to improve the precision of CO2 equivalent emissions calculations by ensuring no unintended truncation occurs during these calculations, allowing for more accurate reporting.

<dev> fix (manual input) [ON-4284] fix CO2Eq Calculations

---

app/src/backend/UnitConversionService.ts
app/src/backend/formulas.ts

we were rounding very small numbers (10^-5) to 1, messing up the calculation
Correct the CO2Eq calculation by fixing a typo in the fuel type key and removing the rounding logic in the emissions calculation.
The typo in the fuel type key prevented the system from accurately identifying fuel data, potentially causing errors or inaccuracies in emissions calculations. The removal of the rounding logic aims to improve the precision of CO2 equivalent emissions calculations by ensuring no unintended truncation occurs during these calculations, allowing for more accurate reporting.

<main> fix (manual input) [ON-4284] fix CO2Eq Calculations

---

app/src/i18n/locales/de/manage-subsectors.json
app/src/i18n/locales/en/manage-subsectors.json
app/src/i18n/locales/es/manage-subsectors.json
app/src/i18n/locales/fr/manage-subsectors.json
app/src/i18n/locales/pt/manage-subsectors.json

Changes
- Adds missing translations for toast error message
Add translations for the "error-updating-notation-keys" toast error message in multiple language files.
These changes address missing translations for a specific error message to ensure users in German, English, Spanish, French, and Portuguese can understand the toast message related to a failure in updating notation keys, thus improving user experience and localization completeness.

fix: adds mission translations for toast error  message

---

app/src/backend/UnitConversionService.ts

This is a minimal change for ON-4386 so that it includes more types of fuels in the density calculations.
I grepped for all the fuel types we have in the manual input file:
```
grep fuel-type- src/util/form-schema/manual-input-hierarchy.json | sed "s/ //g" | sed s/\"//g | sed s/,//g | sort -u > fuels.txt         
```
Then, I added each to the density table in the calculation service, looking up the density either in ChatGPT or on Google. Most of the time, the density calculation was a really rough estimate.
This fixes the problem that was thrown, where the gas amounts were not calculated if there wasn't an EF for mass for that fuel, or if the density wasn't in the table.
Merging this will unblock a release blocker bug, so please let me know when it's done!
Add additional density values …

Add more density values for different kinds of fuels

---

app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx
app/src/backend/ResultsService.ts

Also fixes that some of the rows in the table weren't full width by using React.Fragment instead of <> or <Box>, so the key attribute can be supplied to it but the rows are direct children of the table body.
Replace `Box` components with `React.Fragment` in `ByScopeView.tsx` and refactor emission calculations to improve accuracy and replace `bigIntToDecimal` conversions with `Decimal` in `ResultsService.ts` for calculating subsector emissions percentage accurately in reports.
The `React.Fragment` usage instead of `Box` is intended to eliminate redundant DOM nodes and improve rendering performance. The refactoring in `ResultsService.ts` is aimed at fixing issues where emission percentages were inaccurately calculated due to improper usage of `bigIntToDecimal`, allowing for more precise …

fix(api, ui): 0% of sector emissions on report sector table

---

app/next.config.mjs
app/src/app/api/v0/oauth/metadata/route.ts
app/src/middleware.ts
app/tests/api/oauth_discovery.jest.ts

In reviewing libraries to suggest for POC clients, I found that a lot of them used [RFC 8414](https://datatracker.ietf.org/doc/html/rfc8414) for configuration, figuring out the right endpoints and options for the OAuth process. The RFC defines an url, `/.well-known/oauth-authorization-server`, which should return a JSON object with certain properties that describe the layout and configuration of the OAuth 2.0 server. Note that the endpoint has to be at that specific URL on the server; see [RFC 8615](https://datatracker.ietf.org/doc/html/rfc8615) for a description of how Well-Known URIs work.
This PR implements the endpoint. It uses the `rewrites` feature of NextJS to avoid having a ".well-known" directory, which would be a hidden directory on Unix-like systems (because of the initial …

feat: OAuth Discovery

---

app/src/components/Modals/activity-modal/activity-modal-body.tsx
app/src/hooks/activity-value-form/use-emission-factors.ts

Changes
- Modifies emission factors filter (FE) to include kg/kg units
- Sets fallback units for emission factors
- Dynamilly renders units from emission factors data
Update the calculation and display logic for emission factors to dynamically determine and show correct units based on IPCC methodology, including support for "kg/kg" units.
These changes ensure that the emission factors are displayed with the appropriate units according to the methodology by removing hardcoded unit assignments and enabling dynamic detection, which improves accuracy and flexibility in the emission factor module. The addition of "kg/kg" further supports broader applicability in various scenarios, aligning with user needs and IPCC standards.
> Is this description stale? Ask me to generate a new description by …

fix: show correct emission factors for masses from ipcc
