Open-Earth-Foundation/CityCatalyst

.github/workflows/web-actions.yml, app/README.md, app/env.example, app/src/app/[lng]/auth/check-email/page.tsx, k8s/cc-web-deploy.yml
Also add documentation for new env vars and fix a wrong link on check email page
=> Fix: Auth related errors in Github Actions and k8s

app/README.md, app/package-lock.json, app/package.json, app/seeders/20230927132757-gpc.cjs
Creates a seeder script in app/seeders that reads the CSV files for the GPC data and adds them into the database in a transaction.
Resulting database entries:
```
citycatalyst=# select * from "Sector";
sector_id               |                    sector_name                    |       created       |    last_updated     
--------------------------------------+---------------------------------------------------+---------------------+---------------------
501ace3b-f63f-3267-bd57-69ad6ff5ab77 | Other Scope 3                                     | 2023-09-21 00:00:00 | 2023-09-21 00:00:00
6e986105-3df9-30de-8997-041d93537278 | Industrial Processes and Product Uses (IPPU)      | 2023-09-21 00:00:00 | 2023-09-21 00:00:00
d5acb72e-d915-310f-b3a3-77f634bcbf5e | Waste …
```
=> GPC Seeder for app

app/src/app/api/v0/city/[city]/inventory/[year]/sector/[sector]/subsector/[subsector]/subcategory/[subcategory]/route.ts
Changes
- fixes a request method name
=> fix: changed request method name for subcategory

app/next.config.mjs, app/src/components/Sections/Footer.tsx, app/src/util/helpers.ts
Changes
- Adds file system and path approach to import the package,json file
- Adds helper function to extract package version string
- Adds version tag to footer
=> feat: added helper function to extact the package version

global-api/importer/datasource_seeder/climatetrace_seeder.py, global-api/importer/datasource_seeder/edgar_seeder.py
This PR updates the names in the datasources seeder so they look nicer in the UI
=> Improve readability of names for climatetrace and edgar datasources

global-api/importer/datasource_seeder/climatetrace_seeder.py, global-api/importer/datasource_seeder/edgar_seeder.py, global-api/importer/datasource_seeder/utils.py
This PR add `third_party` to the `source_type` field and now upserts records.
=> Upsert records into datasource 

global-api/importer/datasource_seeder/README.md, global-api/importer/datasource_seeder/import_seeders.sh
=> feat: add script and doucmentation to import seeders

app/package-lock.json, app/package.json
=> fix: added missing package

app/src/app/api/v0/city/invite/[invite]/route.ts
changes
- adds environment host url as redirect when user token gets verified
=> fix(api): use environment host as redirect url

.github/workflows/global-api-develop.yml, global-api/requirements.txt, global-api/tests/test_main.py
basic unit tests for global api end points and automatic comment for test report
=> basic global-api testing

app/src/backend/DataSourceService.ts
Uses the first part of the city locode in order to do data source matching to a specific country
=> fix(api): use country from city locode in geographicalLocation source matching

.github/workflows/global-api-develop.yml
=> global-api testing updated .env name

app/src/app/[lng]/[inventory]/data/[step]/page.tsx, app/src/app/[lng]/[inventory]/data/[step]/types.d.ts
=> feat(ui): show progress indicator for unfinished subsectors in list

global-api/import_everything.sh, global-api/importer/custom_polygons/custom_polygon_subsaharan.py
added polygons for RW KGL, NG ABV, NG LOS, SL FNA
=> feature new custom polygons

app/src/app/[lng]/[inventory]/data/review/page.tsx
Changes
- Replaces hard coded year with inventory year value
=> fix(ui): Replaces hard coded year with inventory year value 

app/src/app/[lng]/[inventory]/settings/page.tsx, app/src/components/Tabs/my-files-tab.tsx
Changes
- Uses Circle flag component to show correct flag for the city
=> fix(ui): show right flag for city

app/src/app/[lng]/[inventory]/data/[step]/SubsectorDrawer.tsx
Changes
- Fixes error state in the manual input form
=> fix(ui): manual input form state errors

app/src/app/[lng]/[inventory]/data/[step]/page.tsx, app/src/components/Modals/add-file-data-modal.tsx, app/src/components/Modals/delete-file-modal.tsx, app/src/features/city/inventoryDataSlice.ts, app/src/i18n/locales/en/data.json
Changes
- Adds file upload functionality for each file added to the sector, 
- Appends the response data to state for review
- Adds file deletion that removes file from database and state
- Adds translation
- modified redux inventoryData to include cityId
- changed file upload modal button text to correct one
=> fix(ui): save uploaded file to database immediately

app/migrations/20240424131954-add-country-region-locode.cjs, app/src/app/[lng]/onboarding/setup/page.tsx, app/src/models/City.ts, app/src/services/api.ts, app/src/util/validation.ts
Also gets the values from OpenClimate data during onboarding
=> feat(api): add countryLocode and regionLocode to city

app/src/app/[lng]/onboarding/setup/page.tsx
Also fixes the arrows on the onboarding year dropdowns not being clickable
=> fix(ui): NaN text on population year dropdowns on onboarding page

app/src/app/[lng]/onboarding/setup/page.tsx
addCity has area as optional but doesn't accept null for it
=> fix(ui): area null passed to addCity route

global-api/importer/argentinian_datasets/BEN/README.md, global-api/importer/argentinian_datasets/BEN/processed_BEN_AR.csv, global-api/importer/argentinian_datasets/BEN/transformation_BEN_AR.py
This PR contains:
- Conversion units fix in transformation file
- New processed csv file
- Folder name changed
=> fix:convertion_units_activity_values

global-api/migrations/versions/c360f7e67f44_fix_column_type_activity_emissions.py
This PR contains:
- new migration file to change column types to string to float in country table for emissions_value and activity_value
=> fix:column_types

global-api/migrations/versions/1973e633eea5_rename_geography_table_to_dim_geography.py
geography table name has a name conflict with postgis extention
=> migration file for table name change

.gitignore, app/README.md, app/env.example, app/src/app/[lng]/onboarding/setup/page.tsx, app/src/i18n/locales/de/onboarding.json
Added toast error for failed validation on adding a new city and updated the command to set up the UI App
=> Added toast error for failed validation on adding a new city 

global-api/importer/emission_factors/carbon_footprint/README.md, global-api/importer/emission_factors/carbon_footprint/clean_raw_data.py, global-api/importer/emission_factors/carbon_footprint/extraction.py
this PR contains:
- README file
- extraction script
- cleaning script
for Carbon FootPrint International Electricity Factors
=> raw emission factors scope 2

app/src/app/[lng]/[inventory]/cdp/page.tsx, app/src/i18n/locales/en/cdp.json
adds placeholder page for cdp data submission
=> adds placeholder page for cdp data submission

app/src/app/[lng]/[inventory]/page.tsx
Replaces undefined (or other invalid inventory IDs) in dashboard URL with default inventory ID and correctly loads the default inventory instead
=> fix(ui): dashboard crash when navigating to /en/undefined

app/src/app/[lng]/[inventory]/data/[step]/SourceDrawer.tsx, app/src/i18n/locales/en/data.json
changes
- Adds number formatting to json
- Applies number formatting to total emission
=> feat(ui): adds i18n number formatting

app/src/features/city/subsectorSlice.ts
https://openearth.atlassian.net/jira/software/projects/OC/boards/4?assignee=712020%3A426e5fcf-d8b1-4692-bae1-5fe35e7f0391&selectedIssue=OC-1430
=> fix: set "scaled sample data" as disabled ("coming soon") [OC-1430]

app/src/components/Modals/add-activity-modal.tsx, app/src/util/form-schema/sector-form-schema.json
Changes
- Adds options for addons which fixes input issue for emission factor values
- Updates form modal
=> fix(ui): adds addon options for emission factor values

app/package-lock.json, app/package.json, app/src/util/form-schema/sector-form-schema.json
Fixes an issue with the sector-form-schema.json file causing the app to crash, also adds @next/env to package.json (necessary for the create-admin script to work)
=> fix: sector-form-schema.json

app/src/util/form-schema/manual-input-hierarchy.json
=> feat: add manual input definitions for sector II

app/migrations/20240805110810-activity-value-co2eq.cjs, app/src/app/api/v0/inventory/[inventory]/activity-value/[id]/route.ts, app/src/app/api/v0/inventory/[inventory]/activity-value/route.ts, app/src/app/api/v0/inventory/[inventory]/value/[subcategory]/route.ts, app/src/backend/CalculationService.ts, app/src/models/ActivityValue.ts, app/tests/api/inventory.test.ts
=> Manual input formulas & saving

global-api/alembic.ini, global-api/import_argentiniandatasets.sh, global-api/import_everything.sh, global-api/importer/datasource_seeder/README.md, global-api/importer/datasource_seeder/datasource_seeder.yaml, global-api/importer/datasource_seeder/import_dataseeder.py, global-api/importer/datasource_seeder/import_datasource_seeder.sql, global-api/migrations/versions/14281ed38551_merge_heads.py, global-api/migrations/versions/77d1cb7b24df_allowing_other_languages.py, global-api/migrations/versions/f8f5b2a87fff_merge_heads_from_develop_and_languages.py, global-api/routes/catalogue_endpoint.py
Reverts Open-Earth-Foundation/CityCatalyst#622
=> Revert "Revert "Implement translations for data source seeder/ data catalogue route""

app/src/util/form-schema/index.ts, app/src/util/form-schema/manual-input-hierarchy.json
For the suggestedActivities data structure, the extra fields to prefill are provided as an array of Prefill objects, each with a key-value pair.
This commit updates the type information and the manual input JSON.
=> feat: use prefills property on suggestedActivities

app/src/app/api/v0/inventory/[inventory]/activity-value/route.ts, app/src/backend/ActivityService.ts, app/src/backend/GPCService.ts, app/src/models/InventoryValue.ts, app/src/util/validation.ts
- Creates GPCService for GPC-related querying functionality (for now getting the subsector/ subcategory/ sector ID for a given GPC reference number)
- Deprecates a bunch of fields that are now in ActivityValue (to be removed later)
=> Allow creating InventoryValue from POST ActivityValue endpoint

app/src/app/[lng]/[inventory]/page.tsx, app/src/components/missing-inventory.tsx, app/src/i18n/locales/de/inventory-not-found.json, app/src/i18n/locales/en/inventory-not-found.json, app/src/i18n/locales/es/inventory-not-found.json
=> Add default page for inventories not accessible to a user

app/src/backend/CalculationService.ts, app/src/util/form-schema/index.ts
With this PR you should be able to save activity forms as well, not just direct measure now and have it correctly calculate the co2eq! :sparkles:
=> Load manual input hierarchy JSON file and search for methodology ID to get formula in CalculationService

app/src/components/Tabs/Activity/activity-tab.tsx
Changes
- Adds target prop that opens tab in different tab when clicked.
=> fix: adds target property to open page gpc protocal page in different tab

app/src/app/[lng]/[inventory]/InventoryCalculationTab.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab.tsx, app/src/app/[lng]/[inventory]/TabHeader.tsx, app/src/app/[lng]/[inventory]/page.tsx, app/src/app/api/v0/inventory/[inventory]/route.ts, app/src/components/Cards/SectorCard.tsx, app/src/i18n/locales/en/dashboard.json, app/src/i18n/locales/en/data.json, app/src/i18n/locales/es/dashboard.json, app/src/util/types.d.ts, app/tests/api/inventory.test.ts
Includes most tickets in https://openearth.atlassian.net/browse/ON-1382
=> [ON-1382] Implement Changes in the Dashboard pt 1

app/src/app/[lng]/[inventory]/InventoryCalculationTab.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab.tsx, app/src/app/[lng]/[inventory]/TabHeader.tsx, app/src/app/[lng]/[inventory]/page.tsx, app/src/app/api/v0/inventory/[inventory]/route.ts, app/src/components/Cards/SectorCard.tsx, app/src/i18n/locales/en/dashboard.json, app/src/i18n/locales/en/data.json, app/src/i18n/locales/es/dashboard.json, app/src/models/Population.ts, app/src/util/types.d.ts, app/tests/api/inventory.test.ts
=> [ON-1383] Total Emissions Widget

app/migrations/20240812130411-adjust-fk.cjs
So that if one thing fails, the rest doesn't
=> remove transaction

global-api/main.py, global-api/migrations/versions/1d9bbf3aff0e_create_modelled_schema.py, global-api/routes/v1_emissions.py
added tables for the modeled schema
added a new emissions route that give the total emissions and the emissions by subcategory
added a parameter for the global warming potential ar2, ..., ar6 this can be used based a users preference
=> feat: added new route for modelled global-api structure

app/src/backend/ActivityService.ts, app/src/backend/CalculationService.ts, app/src/backend/formulas.ts
Gas values were not being passed to the the calculation service formulas
=> fix(api): gas formula calculation error

app/src/app/api/v0/inventory/[inventory]/results/route.ts, app/src/backend/ResultsService.ts, app/src/components/blue-subtitle.tsx, app/src/services/api.ts, app/src/util/helpers.ts, app/src/util/types.d.ts, app/tests/api/results.data.ts, app/tests/api/results.jest.ts
just added tests, nothing for QA
=> [on-2106] top emissions by subsector tests

app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx
=> fix: remove width from Emissions table to avoid scrollbar

app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx, app/src/backend/ResultsService.ts, app/src/i18n/locales/en/dashboard.json, app/src/util/helpers.ts, app/src/util/types.d.ts, app/tests/api/results.jest.ts
Enhanced the Top Emissions Widget with improved data display and internationalization support.
- Added scope information to the top emissions table
- Improved styling of the emissions table for better readability
- Implemented internationalization for table headers and scope labels
- Updated the backend query to include scope information
- Added a new helper function `capitalizeFirstLetter` for text formatting
1. Navigate to the Inventory Results Tab
2. Verify that the Top Emissions Widget displays scope information for each emission
3. Check that the table headers are properly translated
4. Ensure the styling of the emissions table matches the new design
5. Confirm that the scope labels are correctly capitalized
This change provides more comprehensive information about emissions by …
=> [ON-2418] feat: add scope to emissions table

.gitignore, global-api/.gitignore
Also adds .DS_Store and swap files to global .gitignore
=> Move global API specific ignore settings into global-api/.gitignore

app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx, app/src/backend/ResultsService.ts, app/src/lib/app-theme.ts
Accidentally merged before pushing the requested changes for https://github.com/Open-Earth-Foundation/CityCatalyst/pull/726/files/60c255ced33c627d8deee4b25e990d8c996c9976. Here they are.
=> Fixes for PR 726

app/src/app/[lng]/[inventory]/data/[step]/page.tsx
Changes
- Adds correct url path to router push method
- Prettier formatting
=> fix(ui): adds correct url path

app/src/app/api/v0/datasource/[inventoryId]/route.ts, app/src/backend/CalculationService.ts, app/src/backend/formulas.ts, app/src/util/constants.ts, app/src/util/population.ts
TODO: Still needs differentiation of industrial and residential waste, which are two inputs in the same activity that need to be considered in the formula.
=> Implement waste water formula for industrial and domestic activities

app/src/components/missing-inventory.tsx
Changes
- changes zindex value of the missing inventory component
=> fix: changes zindex value of the missing inventory component

app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx, app/src/backend/ResultsService.ts, app/tests/api/results.jest.ts
Querying from inventoryValue instead of ActivityValue
=> (bug) [ON-2522] show connected data on report results

app/src/util/helpers.ts
=> (bug) [ON-2595] number separators

app/src/app/[lng]/[inventory]/InventoryResultTab/ByActivityView.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/ByActivityViewTable.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/SectorHeader.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx, app/src/app/[lng]/[inventory]/data/page.tsx, app/src/app/api/v0/inventory/[inventory]/results/[sectorName]/route.ts, app/src/app/sectors.ts, app/src/backend/ResultsService.ts, app/src/i18n/locales/en/dashboard.json, app/src/services/api.ts, app/src/util/helpers.ts, app/src/util/types.d.ts, app/tests/api/results_sector.jest.ts
Show sector visualization breakdown
=> sector visualization by activity & scope

app/public/assets/report_results_empty_state.svg, app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsWidget.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/EmptyStateCardContent.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/SectorHeader.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx, app/src/app/[lng]/[inventory]/page.tsx, app/src/backend/ResultsService.ts, app/src/i18n/locales/en/dashboard.json
=> ON-2189 report results empty state

app/src/app/[lng]/[inventory]/InventoryCalculationTab.tsx, app/src/i18n/locales/en/dashboard.json
=> fix: [ON-2093] inventory calculation title

app/src/components/ChatBot/chat-popover.tsx
changes
- Removes fixed height property that caused chat components to overflow
=> fix(ui): removes fixed height from climate assistant that caused overflow

app/.vscode/extensions.json, app/playwright.config.ts
Adds Playwright VSCode extension as recommendation for easier user onboarding
=> feat(e2e): add clear test matching case to Playwright config and add Playwright as recommended VS Code extension

app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx
=> [ON-2379] (fix) bigint(undefined) bug

app/src/components/Sections/Footer.tsx
Changes
- Adds missing links to footer quick access links
=> fix(ui): adds missing links to quick access links in the footer section

app/src/components/Sections/Footer.tsx
Changes
- Adds missing contribution link to footer
=> feat(ui): adds missing read the docs link to footer

app/src/app/[lng]/onboarding/setup/FormattedThousandsNumberInput.tsx, app/src/app/[lng]/onboarding/setup/page.tsx
=> feat: [ON-2640] add thousand separators on the onboarding screen

app/src/app/[lng]/[inventory]/page.tsx
=> feat: [ON-1880] add thousands separators in dashboard

app/migrations/20241028135340-inventory__alter__add__published_at.cjs, app/src/models/Inventory.ts
=> feat: [ON-2755] add PublishedAt to inventory

app/src/components/Cards/SectorCard.tsx
=> bug: [ON-2663] fix required scope

global-api/main.py, global-api/migrations/versions/b1e6ab175504_ccra_init_schema.py, global-api/routes/catalogue_endpoint.py, global-api/routes/catalogue_last_update_endpoint.py, global-api/routes/ccra_assessment.py, global-api/routes/city_boundaries_endpoint.py, global-api/routes/city_locode_endpoint_climatetrace.py, global-api/routes/city_locode_endpoint_crosswalk.py, global-api/routes/city_locode_endpoint_edgar.py, global-api/routes/city_locode_endpoint_ghgrp.py, global-api/routes/citywide_emission_endpoint.py, global-api/routes/country_code_endpoint.py, global-api/routes/ghgi_emissions.py, global-api/routes/region_code_endpoint.py, global-api/tests/test_ccra_assessment.py, global-api/tests/test_main.py
- Need to review with the team before merging
=> feat: added ccra schema to global-api

app/src/components/HomePage/HomePage.tsx
=> [ON-2907] fix: year

app/src/app/[lng]/auth/signup/page.tsx, app/src/components/email-input.tsx, app/src/components/icons.tsx, app/src/components/password-input.tsx, app/src/i18n/locales/en/auth.json
Changes
- Adds styling to enhance error feedback
- Adds realtime password validation checklist
- Adds Icons for error messages
**Login Email Validation Error**
**Sign up Form Validation**
=> Auth form validation fixes

app/e2e/auth.setup.ts, app/e2e/onboarding.spec.ts, app/src/app/[lng]/onboarding/done/[cityId]/[year]/[inventory]/page.tsx, app/src/app/[lng]/onboarding/page.tsx, app/src/components/steps/add-inventory-details-step.tsx, app/src/components/steps/add-population-data-step.tsx, app/src/components/steps/confirm-city-data-step.tsx, app/src/components/steps/select-city-steps.tsx
=> Feat: Adds e2e tests for onboarding flow

app/src/app/[lng]/auth/update-password/page.tsx
Changes
- Adds validation check list logic to prevent users from submitting invalid input. Hence the error message `(invalid request)`
=> fix(ui): adds validation for new password input

app/src/components/Tabs/my-inventories-tab.tsx, app/src/util/helpers.ts
Changes
- Replaces hardcoded flag icon with CircleFlag component
- Adds helper function to extract the country locode from `cityLocode` string
=> feat: adds circle flag component and  locode extraction function

app/src/components/Tabs/my-inventories-tab.tsx
Changes
- Resolves null error for city locode
=> resolves null error

app/package-lock.json, app/src/backend/DataSourceService.ts
Only one source for each GPC refno can be connected (also checks for MI data)
=> fix(api): only allow connecting one source per GPC reference number

app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx, app/src/services/api.ts
Fix the display of connected third-party data in the SubSectorPage by correcting parameter names and adding condition checks to the API requests.
The previous implementation failed to handle cases where `subSectorId` was undefined, causing API requests to fail. By introducing a skip condition based on `subSectorId` and refining parameter handling, the UI correctly fetches and displays third-party data, enhancing data visibility and user experience.
=> fix(ui): connected third party data not being shown in MI

app/src/components/steps/add-population-data-step.tsx, app/src/components/steps/chekmark.tsx
Changes
- Adds uses watch to track population and year values to each input
- Uses tracked values to set the check icon component
=> fix(ui): resolves checkmark bug for all population inputs

app/src/components/HomePage/HomePage.tsx
Changes
- Adds condition to reload dashboard page if trailing slash is missing
Ensure the navbar and chat assistant components render correctly by appending a forward slash to the current URL path if it doesn't already end with one.
There was an issue where the navbar and chat assistant would not render properly due to the URL path missing a trailing slash, causing inconsistencies with path recognition. By standardizing the URL format, this fix ensures reliable component rendering while avoiding unnecessary side effects or reloads.
=> fix(ui): navbar and chat assistant not rendering

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorChart.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorTable.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
- Includes some UI updates to charts
-  Language localication of  emission breakdown by sectors table and charts
Enhance data rendering on multi-year emission charts and tables by implementing a `toKebabCaseModified` utility function for consistent sector name formatting and updating chart components for better layout presentation.
The original rendering logic had issues with inconsistent sector name formatting in multi-year charts, leading to incorrect data representation. The `toKebabCaseModified` function standardizes sector names particularly for special cases like "ippu" and "afolu," ensuring consistent data handling. Additionally, layout improvements in the chart component enhance the visual presentation and user experience.
> Is this description stale? Ask me to generate a new …
=> Fix Data rendering issue on multi year charts

app/src/app/api/v0/inventory/[inventory]/activity-value/[id]/route.ts, app/src/backend/ActivityService.ts, app/src/components/Modals/delete-activity-modal.tsx, app/src/models/InventoryValue.ts, app/src/services/api.ts
Implement the deletion of `InventoryValue` when its last associated `ActivityValue` is deleted, update inventory `co2eqYears` calculation, and refine API responses for deletion operations.
The changes ensure data integrity by automatically removing an `InventoryValue` if it no longer has any associated `ActivityValue`, thereby preventing orphaned records. Additionally, recalculating `co2eqYears` fixes a previously unaddressed issue and accurately reflects the state of remaining `ActivityValues`. Changes to the API responses help enforce a consistent return structure, simplifying error handling and success confirmation in the client.
=> fix(api): ON-2989 delete InventoryValue after last ActivityValue

app/src/app/api/v0/inventory/[inventory]/results/[sectorName]/route.ts, app/src/app/api/v0/inventory/[inventory]/results/route.ts, app/src/backend/ResultsService.ts, app/src/models/InventoryValue.ts
Modify the emissions calculation to include third-party emissions by loading `InventoryValues` scoped to each inventory in the results service and update handling in the API route layer.
This change is necessary to ensure accurate emissions reporting by including emissions data from third-party sources when internal activity values are absent. By refactoring the API route and results service, the system can now calculate emissions comprehensively, addressing potential data gaps and improving reporting accuracy.
=> fix(api): load InventoryValues in emissions by scope

app/src/i18n/locales/de/onboarding.json, app/src/i18n/locales/es/onboarding.json, app/src/i18n/locales/pt/onboarding.json
This page is shown when you finish adding an inventory
Add translations for "add new inventory" to German, Spanish, and Portuguese locales and correct a typo in the German translation for "create inventory" on the "inventory created" page.
These changes improve the user experience by ensuring that non-English speaking users can easily understand and navigate the "inventory created" page, and fix a typo that could lead to confusion or errors in the German interface.
=> [ON-3116] fix translations on "inventory created" page

app/src/backend/ResultsService.ts, app/src/models/InventoryValue.ts, app/src/util/form-schema/manual-input-hierarchy.json
Add new industry types and industry names to the manual input hierarchy JSON schema.
These changes expand the existing industrial categories to include "other industries" and provide additional specificity with new industry names, aiming to enhance data categorization and improve user input accuracy within the application. This approach ensures broader coverage and flexibility for industry classification.
=> Extra industry types and names

app/src/components/SegmentedProgress.tsx
see ticket for before and after
https://openearth.atlassian.net/browse/ON-3134
Capitalize the label "total" in the `SegmentedProgress` component, increase the minimum width of the tooltip, add a flex-wrap style to support wrapping of elements, and import a helper function for capitalization.
The capitalization of the "total" label improves consistency and readability, while the increased minimum width of the tooltip ensures proper display when additional content or larger text is present. The added flex-wrap style allows elements to wrap within their container, enhancing the layout's flexibility for different screen sizes. These updates address visual inconsistencies and improve the user interface experience for viewing total emissions in Scopes 4 and 5.
> Is this description stale? Ask …
=> [ON-3037] fix total emissions view For Scopes 4 and 5

app/src/components/Cards/years-selection-card.tsx, app/src/i18n/locales/de/dashboard.json, app/src/i18n/locales/en/dashboard.json, app/src/i18n/locales/es/dashboard.json, app/src/i18n/locales/pt/dashboard.json
Changes
- Adds translations to inventory year component
- Updates translation json files with translation value
Add translations for the "Last Update" label in the inventory year component across multiple languages and integrate the `i18next` TFunction for localization.
The changes ensure that the "Last Update" label in the inventory year component is displayed in the respective language selected by the user, improving the user interface's accessibility and usability for non-English speakers. Including the translation function `TFunction` from `i18next` helps facilitate this localization process.
=> fix(ui): adds transalation to inventory year component

app/package-lock.json, app/package.json, app/src/app/api/v0/inventory/[inventory]/download/route.ts, app/src/backend/CSVDownloadService.ts, app/src/backend/ECRFDownloadService.ts, app/src/util/helpers.ts, app/src/util/types.ts
- Add new functionality for exporting inventory data to CSV by introducing `CSVDownloadService`, updating dependencies to include `csv-stringify`, and refactoring existing types and services to support CSV formatting.
- Include new columns for csv output
```
[
"Inventory Reference",
"GPC Reference Number",
"Subsector name",
"Notation Key",
"Total Emissions",
"Activity Value",
"Activity Units",
"Emission Factor - CO2",
"Emission Factor - CH4",
"Emission Factor - N2O",
"Emission Factor - Unit",
"Datasource ID",
"DataSource name",
]
```
These changes enable users to download inventory data in CSV format, a common and widely supported file type that simplifies data manipulation and visualization. The addition of `CSVDownloadService` centralizes the CSV generation logic, keeping the code …
=> CSV output updates

app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx, app/src/i18n/locales/de/dashboard.json, app/src/i18n/locales/en/dashboard.json, app/src/i18n/locales/es/dashboard.json, app/src/i18n/locales/pt/dashboard.json
Introduce error handling and loading state management for sector breakdown data fetch in the `InventoryResultTab` component, and add new translation strings to support error messaging in multiple languages.
These changes enhance the user experience by providing feedback when data fetching errors occur and manage loading states more effectively. New translation strings were added to accommodate error messages, ensuring that non-English users receive clear notifications in their preferred language.
=> [ON-3148] [ON-3149] Emissions breakdown feedback

app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx, app/src/i18n/locales/en/dashboard.json, app/src/i18n/locales/es/data.json, app/src/i18n/locales/pt/dashboard.json, app/src/i18n/locales/pt/data.json
Correct the casing of "IPPU", "AFOLU", and "Stationary Energy" across various components and localization files in the project.
These changes ensure consistency in text capitalization across the application, improving readability and maintaining stylistic standards. Proper casing also aligns with preferred naming conventions used in domain-specific contexts.
=> [ON-3154] fix casing for IPPU, AFOLU and Stationary energy

app/src/components/ChatBot/chat-bot.tsx, app/src/i18n/locales/de/chat.json, app/src/i18n/locales/en/chat.json, app/src/i18n/locales/es/chat.json, app/src/i18n/locales/pt/chat.json
Also adds acronyms to queries where necessary (for GPC and IPCC so they can be used by the AI model without confusion in other languages).
Translate chat suggestions into supported languages and dynamically utilize translation files for chat suggestions.
These changes enhance the chatbot's user experience by providing translated chat suggestions in German, English, Spanish, and Portuguese, thereby supporting a broader user base. This approach uses translation files instead of hard-coded values to ensure improvements and future translations are easily implemented.
=> fix(ui): translate chat translations into supported languages

app/src/components/Modals/delete-inventory-modal.tsx
Changes
- Adds reset function to handle form reset after submission
Add a reset function to the delete inventory modal component to reset the form after submission.
The form reset function is added to ensure the form is cleared and ready for a new input after a successful submission, improving user experience by preventing data from previous submissions from lingering in the form fields. This change addresses the issue where users may inadvertently submit stale data.
=> fix(ui): adds a reset function that resets form after submission

app/src/components/Cards/methodology-card.tsx, app/src/i18n/locales/de/data.json, app/src/i18n/locales/en/data.json, app/src/i18n/locales/es/data.json, app/src/i18n/locales/pt/data.json
Changes
- Adds a condition to prevent disabled methodologies from being clicked
- Adds a toast message to give users feedback
- Adds translation for en,es,de,pt
Prevent users from clicking on disabled methodologies in the UI and provide a toast notification when a disabled item is clicked.
These changes enhance the user experience by preventing interactions with disabled methodologies, which could otherwise lead to confusion. The toast notification acts as immediate feedback, informing users that their selected methodology is currently unavailable, thereby improving clarity and usability of the application interface.
=> FIX(UI): prevents disbled methodologies from being clicked

global-api/main.py, global-api/routes/ghgi_emission_forecast.py
Add a new API route for emissions forecast under the `GHGI Emissions` category and include a sample response for the city BR SER using hardcoded data.
These changes introduce a feature for projecting future greenhouse gas emissions, addressing a need for assessing emissions trajectories in city developments. The current solution uses hardcoded data as a placeholder until proper database entries are available, providing immediate utility for testing and further development.
=> added route for projections with a sample response for BR SER

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorChart.tsx, app/src/i18n/locales/en/data.json
Enhance the `EmissionBySectorChart` component by adding a custom tooltip that utilizes additional UI elements from Chakra UI, and update the i18n localization file to include a new industry type label.
These changes improve the user experience by providing more informative visual feedback through the use of detailed tooltips in the emissions chart, and expand the localization options to cater to a broader range of industry sectors, addressing the requirements of ON-3119 and ON-3171.
=> [ON-3119] [ON-3171] [ON-3211] small bugs

global-api/routes/ghgi_emission_forecast.py
Divide the `value` by 100 to convert the growth rate from a percentage to a decimal in the `db_city_emission_forecast` function.
The growth rate was previously represented as a percentage, which caused inaccuracies in calculations expecting a decimal format. Adjusting to use decimal format aligns with the standardized representation of growth rates and ensures accurate computations in forecasts.
=> sample projection was a percentage rather than decimal

app/src/components/recent-searches.tsx, app/src/components/steps/select-city-steps.tsx, app/src/i18n/locales/de/onboarding.json, app/src/i18n/locales/en/onboarding.json, app/src/i18n/locales/es/onboarding.json, app/src/i18n/locales/pt/onboarding.json
Changes
Our recent search componet on the onboarding had hardcoded texts, this PR fixes it by adding the following changes:
1. Replaces hardcoded text with translation string functions
2. Adds translations values for en,es,pt,de
Add translations for the recent search component in the onboarding process across English, German, Spanish, and Portuguese locales and update the `RecentSearches` component to support internationalization.
To enhance usability and localization of the application by ensuring text in the recent search feature is translated correctly for users in different regions, promoting a better user experience in multiple languages. This change requires passing the translation function as a prop to the `RecentSearches` component to dynamically display translated text.
> Is this …
=> fix: adds translation for recent search component on onboarding

app/src/backend/OpenClimateService.ts
Add detailed logging to the `getGrowthRatesFromOC` function to track the API URL and response status using a logger service.
These changes were made to enhance debugging capabilities by providing more informative log messages, which will help in tracing issues related to API calls. Using a dedicated logger service allows for consistent and configurable logging across the application.
=> [ON-3215] debug GLOBAL_API_URL

app/src/components/Modals/delete-inventory-modal.tsx, app/src/components/password-input.tsx
Changes
- adds translation string to password input label
Add a translation function to accurately translate the password label in the `DeleteInventoryModal` component.
The changes ensure that the password field label is translated correctly using the `t` translation function, enhancing the internationalization support of the application. This promotes better user experience across different languages by utilizing the right context for translations.
=> fix(ui): adds translation function to translate label correctly

app/src/components/password-input.tsx
Modify the PasswordInput component to handle cases where `error.message` might be undefined by providing a default empty string.
Fix build error
=> [ON-3141] chore: fix build

app/src/backend/GlobalAPIService.ts, app/src/backend/ResultsService.ts, app/tests/api/emissions_forecast.jest.ts, app/tests/api/results.data.ts
Handle missing data from GlobalAPI by returning `undefined` when response status is not 200, and rename the module from `OpenClimateService` to `GlobalAPIService`.
These changes address a bug where the application crash if the GlobalAPI does not return data successfully, improving robustness by returning `undefined` to handle non-200 responses. The module is renamed to better reflect its purpose and promote clearer codebase organization and maintainability.
=> bug: [ON-2864] handle missing data from globalAPI &  rename module

app/src/backend/ResultsService.ts
> [!NOTE]
> I'm currently writing a description for your pull request. I should be done shortly (<1 minute). Please don't edit the description field until I'm finished, or we may overwrite each other. If I find nothing to write about, I'll delete this message.
=> bug: [ON-3263] use inventory year instead of inventory creation date

app/e2e/login.spec.ts, app/e2e/onboarding.spec.ts, app/e2e/signup.spec.ts
signup.spec.ts, login.spec.ts, onboarding.spec.ts are failing on the dev branch. I messaged the team about these errors and will make sure the tests are fixed and un-skipped. But I'm skipping them for now so we don't clog down the pipeline
=> chore: skip failing tests

app/src/components/Modals/delete-inventory-modal.tsx
Changes
- Wraps FormControl content in form tag this allows form submission using the enter key that triggers onsubmit react-hook-form function
- Adds subission loading state to button for better feedback
Add form tags and loading state to the delete inventory modal.
These changes improve user experience by using a form for submitting data and visually indicating when a delete action is processing, adding clarity and preventing duplicate submissions.
=> fix: adds form tags, is loading state to modal

app/src/app/api/v0/auth/password/route.ts
Changes
- adds error handling for password reset token this way we do get a user not found error when it expires
Improve token verification error handling in the password reset route by adding specific error checks for token expiration and invalid tokens, and providing more informative error messages.
The previous implementation did not differentiate between expired and invalid tokens, leading to generic error messages that could confuse users. By specifically identifying the type of token error, we can return more user-friendly messages and improve the overall user experience during password resets.
=> fix: adds better token verification error handling

app/src/components/HomePage/AddCollaboratorModal/MultipleEmailInput.tsx
Refactor the `MultipleEmailInput` component to enhance styling consistency by updating text components, adding spacing with margins, integrating a divider, and modifying tag styles.
These changes address issue ON-2779 by ensuring visual alignment with the design specifications, enhancing user experience with clearer spacing and improved element visibility, and utilizing consistent styling components across the application. This approach resolves the bug related to inconsistent styling without introducing functional changes.
=> bug: [ON-2779] fix styling

app/src/lib/emails/InviteUserToMultipleCitiesTemplate.tsx
Refactor the email template's city box styling to enhance layout consistency and replace the `Text` component with a `div` for city names.
The changes fix a visual bug in the email template by correctly aligning flag images with their respective city names and ensuring a consistent appearance by adjusting styling properties and using a `div` instead of a `Text` component. This approach simplifies the style management and resolves issues related to text positioning and layout in the email rendering.
=> bug: [ON-2797] fix email format

.github/workflows/web-develop.yml, app/Dockerfile
Update the Docker build process to include build arguments for `NEXT_PUBLIC_API_URL` and `NEXT_PUBLIC_OPENCLIMATE_API_URL`, and set these as environment variables for the Next.js build process.
The changes ensure that the application has access to necessary environment-specific URLs during the build process, which allows the application to interact correctly with external APIs in the test environment without hardcoding these URLs in the source code. This approach improves flexibility and makes the application more adaptable to different deployment contexts.
=> fix: update build process

app/src/app/api/v0/user/invites/[cityInviteId]/route.ts, app/src/backend/UserService.ts, app/src/components/Tabs/MyProfileTab/ManageUsersTabPanel.tsx, app/src/components/Tabs/MyProfileTab/ManageUsersTable.tsx
Implement pagination in the `ManageUsersTable` component, improve query efficiency by replacing parameters in SQL statement, and clean database service logging output.
The changes enhance user experience by allowing users to navigate large lists of invites more efficiently with pagination, replace a redundant user ID filter with an optimized one for improved query performance, and remove unnecessary logging data to simplify the debugging process and improve readability.
=> [on-2797] Korbit comments

app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx, app/src/lib/app-theme.ts
Limit the display of top emissions in the `TopEmissionsWidget` to three items and update several sector color codes in the app's theme.
Reducing the number of top emissions displayed improves readability and user experience by focusing only on the most significant data points. The color updates align with new design guidelines, ensuring visual consistency and improved accessibility.
=> [ON-3265] update colors

app/Dockerfile
Fixes build issue about dev dependencies not being installed during `docker build` while keeping the dev dependencies outside of the resulting image to keep the size small(er)
Set up a multi-stage build process in the Dockerfile for the application, separating the build stage and the production stage.
Implementing a multi-stage build decreases the final image size by separating the build dependencies from the runtime environment, enhancing performance, and optimizing deployment in production. This approach ensures only necessary production dependencies are included, aligning with best practices for Docker container optimization.
=> feat(api): set up multi stage build in Dockerfile for app

app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx, app/src/util/helpers.ts
Fix the translation of subsector names by utilizing the `toKebabCase` helper function to format activity titles consistently before translation.
The subsector names were not being translated correctly due to inconsistent formatting, which led to translation mismatches. Using the `toKebabCase` function ensures that activity titles are properly formatted and consistent, thereby improving translation accuracy and user experience.
=> [ON-3316] fix translation of subsector names

app/Dockerfile
Add the migrations and config directories to the production Docker image for executing migrations.
The Docker image was missing the necessary migrations and config folders, which prevented the application from running database migrations during deployment. Including these directories ensures that the application can perform migrations correctly, enabling a smoother and functioning deployment process.
=> fix(deploy): docker image missing migrations and config folder to execute migrations

app/src/components/steps/add-inventory-details-step.tsx, app/src/components/steps/add-population-data-step.tsx, app/src/components/steps/select-city-steps.tsx
Refactor UI components for better styling consistency on onboarding screens by updating styling properties and restructuring components using Chakra UI v3, focusing on eliminating deprecated `Group` usage and enhancing form feedback features.
The transition to Chakra UI v3 introduced styling inconsistencies and deprecated components, necessitating an update to meet the new requirements and ensure a seamless user experience on onboarding screens. The refactoring also aims to improve code maintainability and visual feedback for form interactions.
=> fix(ui): styling issues on onboarding screens for Chakra UI v3

app/src/components/Tabs/my-inventories-tab.tsx
Changes
- Adds function to convert inventory lastUpdated string to data object and returns a formatted date
Add a function to convert the `lastUpdated` string in inventory data to a formatted date for display.
The change addresses the need to dynamically convert and display the last update date for inventories, replacing the previously hardcoded date. This allows for more accurate and contextually relevant information for users. Additionally, the function includes error handling for invalid dates, ensuring robust performance.
=> fix: adds function to convert last update string

app/package-lock.json, app/package.json, app/src/app/[lng]/layout.tsx, app/src/util/feature-flags.ts
Introduce feature flags and runtime environment variables support in the application using `next-runtime-env`.
These changes allow the application to dynamically handle feature flags through environment variables, making it easier to enable or disable features without redeploying. This approach also enables managing configuration more efficiently for different deployment environments, leveraging the `next-runtime-env` package for seamless integration with Next.js applications.
=> feat(ui): implement feature flags, runtime environment variables

app/src/app/[...not_found]/page.tsx, app/src/components/missing-inventory.tsx
Fixes users getting a 404 page after first signup and then login, so they couldn't use the platform
Update routing logic in the NotFound and MissingInventory components to redirect users to the root or /onboarding path when the inventory is missing, and replace hardcoded support emails with an environment variable.
The prior logic erroneously attempted to push a nonexistent or missing inventory ID, which could lead to user errors. By redirecting users to the /onboarding path or root, the UX is streamlined, guiding users appropriately when inventory data is unavailable. Additionally, using an environment variable for support emails increases maintainability and prevents the need for code changes if email addresses are updated.
> Is this description stale? Ask me to generate a new …
=> fix(ui): redirect to /onboarding when inventory is missing

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorChart.tsx, app/src/components/ChatBot/chat-popover.tsx
Refactor the chat popover's close button handler to manage open and close states effectively in a more streamlined manner.
The existing implementation did not properly handle the states when closing the chat popup, leading to potential user interface issues. By introducing the `onOpenChange` handler, we can more accurately manage the open/close states and ensure that cleanup operations are called appropriately after the popup is closed, which improves maintainability and user experience.
=> fix: close button handler on ai chat popup

app/src/components/ui/switch.tsx
Changes
- Adds border radius property switch component
- Adds prettier formatting
Add a specific border radius of "16px" to the `ChakraSwitch.Control` component in the `ui/switch.tsx` file.
These changes are made to ensure a consistent and visually appealing UI component by specifically defining the border radius. It addresses a design specification or feedback requiring that the switch component's corners be rounded to a precise measurement rather than relying on any default styles.
=> fix: switch border radius

app/src/components/Tabs/MyProfileTab/ManageCitiesTabPanel.tsx
Changes
- adds extra column to fix missing border
Add an extra empty column header to the ManageCitiesTabPanel component to correct a missing border.
The missing border issue is visually impacting the UI layout, causing an inconsistency in the table's appearance. Adding an extra column header ensures that the border renders correctly across the entire header row, providing a consistent and visually appealing interface.
=> fix(ui): [ON-3553] adds extra column to fix missing border

app/src/components/Tabs/MyProfileTab/ManageUsersSubTable.tsx, app/src/components/Tabs/MyProfileTab/ManageUsersTable.tsx
Refactor `ManageUsersSubTable.tsx` to use hooks (`useCallback`, `useEffect`) for handling button click handlers and toast notifications, and update the style of badges by adjusting text, border, and background colors based on invite status; remove unused imports from `ManageUsersTable.tsx`.
These changes optimize the rendering performance by memoizing functions with `useCallback` and improving state management with `useEffect`, while ensuring better styling control over badges for visual consistency. The removal of unused imports in `ManageUsersTable.tsx` helps in cleaning up the codebase and reducing potential bundle size.
=> Nina/bug/on 3371/fix badge style

app/src/app/[lng]/auth/signup/page.tsx
Implements automatic login into the platform after signup and removes verify page from signup flow
Implement automatic login after signup to enhance the user flow in the signup process.
Previously, users had to manually log in after signing up, which was inconvenient and fragmented the user experience. By implementing automatic login after signup, we improve the seamlessness and efficiency of the onboarding process, enhancing user satisfaction and potentially increasing retention. This adjustment temporarily bypasses the email verification to prioritize user flow and may be revisited when verification becomes necessary again.
=> feat(ui): implement automatic login after signup

app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsForecast/GrowthRatesExplanationModalTable.tsx
Add striped rows to the GrowthRatesExplanationModalTable to improve readability.
This change addresses a readability issue identified in the UI, enhancing user experience by making it easier to track data across the table rows. Striped tables are a common design solution for avoiding visual confusion, especially in data-heavy displays.
=> bug(emissions forecast)[ON-3100] add stripes to table

app/src/app/api/v0/inventory/[inventory]/notation-keys/route.ts
Implement a basic notation key creation endpoint for the inventory API.
This change addresses the need for a dedicated endpoint that allows users to create or update notation keys for specific sub-sectors within an inventory. The approach ensures that each notation key is appropriately validated and managed in the database, enhancing data integrity and supporting user requirements for tracking and explaining unavailable inventory data.
=> feat(ui): ON-3536 implement basic notation key creation endpoint

app/src/components/InventorySelect.tsx, app/src/components/navigation-bar.tsx
For inventory, language and user menus
Implement the "solid" menu variant for menus in `InventorySelect` and `navigation-bar` components, and adjust icon colors to change when highlighted.
The changes improve the user interface by providing a consistent visual style using the "solid" menu variant, which enhances the visual appearance of the application. Additionally, changing the icon colors when highlighted improves user interaction feedback, making it clearer which menu item is currently selected or being interacted with.
=> feat(ui): use solid menu variant and adjust icon colors when highlighted

app/src/components/ChatBot/chat-bot.tsx
Disable the automatic scroll-to-bottom functionality in the chat bot component by commenting out related code segments.
The automatic scroll feature has been temporarily disabled due to user feedback indicating that it disrupts the user experience by interfering with manual scrolling. This approach allows for manual control of scrolling while maintaining the original code for potential future re-enablement.
=> fix(ui): ON-3562 disable scroll to bottom in chat bot

app/migrations/20250306122357-adds_organization_table.cjs, app/migrations/20250306124233-adds_project_table.cjs, app/migrations/20250306131022-adds_project_id_to_city_table.cjs, app/migrations/20250306133212-adds_default_project_id_to_user_table.cjs, app/migrations/20250306133212-adds_default_project_id_to_user_table.js, app/migrations/20250306152003-remove_user_reference_from_org_table.cjs
Create `Organization` and `Project` tables, add `project_id` column to the `City` table, and add `default_project_id` column to the `User` table within the database.
These changes are being made to enhance the database schema by establishing new entity tables for `Organization` and `Project` while ensuring referential integrity across existing tables. These migrations enable associations necessary for the application to organize projects under entities and assign default projects to users, paving the way for improved data organization and query efficiency.
=> feat(gtm):[on-3546] create org, and project tables

global-api/migrations/versions/77b87d254c95_add_priority_column_to_raw_data_.py
Add a `priority` column to the `datasource` table within the `raw_data` schema.
The addition of the `priority` column facilitates prioritization within the `datasource` table, improving data management for processing tasks. This approach allows for flexible modeling of priority as a `Numeric` value, accommodating various precision needs while ensuring backward compatibility via nullable fields.
=> feat: add 'priority' column

app/src/app/api/v0/user/[userId]/route.ts, app/src/components/Loading.tsx, app/src/components/Tabs/MyProfileTab/AccountDetailsTabPanel.tsx, app/src/components/email-input.tsx, app/src/services/api.ts, app/tsconfig.json
Remove the `role` attribute from the user data model and its associated components, and enhance the user interface by introducing a new `Loading` component for improved user experience during data fetching.
The `role` attribute was determined to be unnecessary for the current scope and has been removed to simplify user data management. The addition of a `Loading` component addresses the need for visual feedback when user data is being fetched, thus improving the user interaction flow. By refactoring the relevant parts of the codebase, these changes aim to streamline the application's functionality while enhancing the user interface.
=> [on-3599] [ON-3602] fix missing email placeholder, remove "role" from settings

global-api/routes/catalogue_endpoint.py
Refactor the datasource endpoint by introducing a `generate_csv_response` helper function for CSV conversion and updating the SQL queries to include the `priority` column. 
These changes aim to improve code maintainability by reducing code duplication through a helper function and ensuring the datasource endpoint correctly includes the `priority` field in its output. The SQL query updates streamline data fetching to align with evolving data requirements.
=> fix datasource end point

app/src/components/Tabs/Activity/external-data-section.tsx
Refactor the card layout of the `ExternalDataSection` component by replacing `Tag` elements with `Badge` and moving child components inside `Card.Body`, alongside adding styling enhancements.
These changes improve the UI consistency and maintainability by using the more appropriate `Badge` component for displaying data quality information, following the design system specifications, and by enhancing the card layout structure for better styling and alignment of components.
=> fix(ui): card layout and badge on ExternalDataSection

global-api/main.py, global-api/migrations/versions/a11d9fd3c3eb_add_city_attribute_table.py, global-api/routes/city_context.py
Add a new city context route to the API for retrieving contextual data about cities and create a new database migration to add a `city_attribute` table.
These changes are being made to introduce a new feature to the API that allows users to access detailed contextual information about cities using locodes. By adding the `city_attribute` table, we store relevant city data in a structured format, enhancing our ability to organize and query city attributes effectively. The route and migration work together to provide a robust backend structure and API functionality for accessing city-specific information.
=> feat: add city context route

app/src/app/api/v0/admin/bulk/route.ts, app/src/app/api/v0/admin/update-inventories/route.ts, app/src/backend/AdminService.ts, app/src/backend/OpenClimateService.ts, app/src/util/constants.ts, app/tests/api/admin.jest.ts
Implement a new admin API route for updating inventories and enhance the backend services with additional inventory attributes and city boundary data.
These changes address the need for administrators to update inventories efficiently and consistently across multiple city codes and years while ensuring data integrity by including crucial geographical information. Adding these capabilities improves data accuracy and enhances functionality for batch operations in inventory management.
=> feat(api): add missing city data, add update inventories route

app/src/app/[lng]/admin/layout.tsx, app/src/app/[lng]/admin/organization/[id]/layout.tsx, app/src/app/[lng]/admin/organization/[id]/profile/page.tsx, app/src/app/[lng]/admin/organization/[id]/projects/page.tsx, app/src/app/[lng]/admin/organization/[id]/team/page.tsx, app/src/app/[lng]/admin/page.tsx, app/src/app/api/v0/organizations/[organizationId]/route.ts, app/src/hooks/Toasts.tsx, app/src/i18n/locales/en/admin.json, app/src/services/api.ts, app/src/util/types.ts
Uploading account_detail_page.mov…
Implement the account details page for the admin organization section including the profile, team, and projects subpages, and update relevant routes and API methods to support this functionality.
These changes provide administrators with a structured UI to view and manage organization details, improving the usability and maintenance of organizational data within the application. By enhancing the navigation and incorporating real-time data fetching and updating, administrators can efficiently manage profiles, team compositions, and projects. Additionally, the API enhancements facilitate these interactions by ensuring that organizational structures are correctly represented and manipulated within the system.
> Is this description stale? Ask me to generate …
=> UI: [on-3607]: create account details page

app/src/backend/ProjectsService.ts
Implement null checks with logging for missing projects and organizations in the `fetchUserProjects` method of the `ProjectService` to prevent errors.
These changes are being made to ensure the system gracefully handles cases where projects or organizations are missing, preventing potential runtime errors and improving the robustness of the application. Using logging allows issues to be tracked and analyzed without interrupting user experience.
=> fix(api): prevent error in user projects route with missing project/ org

app/migrations/20250403150620-set_default_project_for_existing_cities.cjs, app/src/app/[lng]/admin/CreateOrganizationModal.tsx, app/src/app/[lng]/admin/organization/[id]/profile/page.tsx, app/src/app/[lng]/onboarding/layout.tsx, app/src/app/[lng]/onboarding/setup/page.tsx, app/src/app/api/v0/city/[city]/route.ts, app/src/app/api/v0/city/route.ts, app/src/backend/ProjectsService.ts, app/src/components/HomePage/ProjectDrawer.tsx, app/src/components/navigation-bar.tsx, app/src/components/steps/select-city-steps.tsx, app/src/services/api.ts, app/src/util/validation.ts, app/tests/api/city.jest.ts
Set a default project ID for cities without project assignments and improve UI error handling with optional chaining and feature flagging.
Cities without project IDs were causing UI inconsistencies and errors, especially in environments where project assignments are mandatory. By defaulting to a predefined project ID, these issues are mitigated. Optional chaining and feature flagging enhance robustness and control over project-related UI elements.
=> Fix: UI bugs for cities without Project Ids

global-api/migrations/versions/df2243cdb86d_create_climate_actions_table.py
This adds a migration to the global API to add a climate_action table.
Add a new `climate_action` table to the global API, introducing columns to capture various attributes and constraints related to climate actions, including fields for co-benefits, GHG reduction potential, and adaptation effectiveness.
This change is implemented to enhance the data model by providing a structured way to store and manage information about various climate actions, which will support more comprehensive data analysis and reporting. The constraints and checks ensure data integrity and consistency, aligning with the needs of projects aiming to monitor climate-related efforts effectively.
=> feat: climate_action table in global API [ON-3739]

global-api/Dockerfile
Fixing dockerfile
Add a command to upgrade pip, setuptools, and wheel during Docker image build.
Ensuring that the latest versions of pip, setuptools, and wheel are used helps avoid compatibility issues and takes advantage of the most recent features and security improvements during the installation of dependencies.
=> fix: updating dockerfile

app/src/app/[lng]/[inventory]/CapTab/s3.tsx
Switch environment variable access from `process.env` to `env` in the s3.tsx file.
The update utilizes `next-runtime-env` for improved environment variable management, ensuring consistency and avoiding errors from direct `process.env` access, which is beneficial for runtime configuration and future scalability. This also aligns with best practices for managing public environment variables in Next.js applications.
=> (microsprint) env fix

app/migrations/20250403142438-clear-old-emissions-factors.cjs
Create a new database migration that selects emissions factors with null inventory IDs for removal from the `EmissionsFactor` table.
This change addresses the need to clean up the database by removing outdated emissions factors that are no longer associated with any inventory, reducing redundancy and optimizing storage. This approach was chosen as a means to maintain data integrity and improve overall system performance.
> [!NOTE]
> I'm currently writing a description for your pull request. I should be done shortly (<1 minute). Please don't edit the description field until I'm finished, or we may overwrite each other. If I find nothing to write about, I'll delete this message.
=> feat(db): ON-3704 create migration that removes old emissions factors

.github/workflows/web-tag.yml
Add AWS credentials to the `web-tag.yml` GitHub Actions workflow file for deploying configurations.
The inclusion of AWS credentials in the workflow is necessary for accessing AWS services, such as storing and retrieving data from an S3 bucket, as part of the deployment process. This change ensures that automated deployments can leverage AWS resources securely by using stored secrets.
=> add AWS credentials to web-tag.yml

app/package-lock.json, app/src/backend/CSVDownloadService.ts, app/src/backend/DataSourceService.ts, app/tests/api/datasource_service.jest.ts
Add breakdown of emissions, including specific gas emissions and emission factors, to the CSV file download functionality within the `CSVDownloadService`.
These changes provide a more detailed view of emission data, enabling users to distinguish between emissions of different gases (CO2, CH4, N2O) and their respective emission factors. This enhancement is necessary to improve the granularity and utility of the CSV data for analysis and reporting purposes. Additionally, it refines the handling of activity types and emissions within the service.
=> feat: [on_3755] add break down of emissions to csv file

app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx, app/src/backend/UnitConversionService.ts, app/src/util/form-schema/manual-input-hierarchy.json
Add conversion rules for new fuel units in the `UnitConversionService` and use `Decimal.js` for precise calculation of inventory percentage in `InventoryResultTab`.
These changes enhance the system by supporting new unit conversion capabilities for different fuel measurements, which is necessary due to expanded fuel unit options. The adjustment to `Decimal.js` ensures more accurate calculations, addressing precision issues seen with floating-point arithmetic in JavaScript.
=> Adds conversion rules for new fuel Units

app/package-lock.json, app/src/app/[lng]/admin/page.tsx, app/src/app/[lng]/auth/signup/page.tsx, app/src/app/[lng]/cities/page.tsx, app/src/app/[lng]/onboarding/setup/page.tsx, app/src/app/[lng]/organization/invites/page.tsx, app/src/app/[lng]/user/invites/page.tsx, app/src/app/api/v0/emissions-factor/route.ts, app/src/app/api/v0/organizations/[organizationId]/invitations/accept/route.ts, app/src/app/api/v0/organizations/route.ts, app/src/backend/ProjectsService.ts, app/src/components/HomePage/ProjectDrawer.tsx, app/src/components/NoAccess/index.tsx, app/src/components/navigation-bar.tsx, app/src/components/steps/select-city-steps.tsx, app/src/i18n/locales/en/auth.json, app/src/i18n/locales/en/not-found.json, app/src/lib/auth.ts
Enhance the invitation flow by removing unnecessary project tabs, improving data handling and loading components, adding validation checks, simplifying certain functional logic, and refining the UI/UX elements related to user navigation and organization management, alongside related code optimizations.
To streamline the user invitation process and improve the overall user experience, addressing code redundancy, enhancing UI feedback mechanisms, and ensuring robust validation and authorization across the invitation management system. This also includes structural cleanup for better maintainability and potentially improved performance of the application.
=> fix invitation flow

app/src/app/[lng]/organization/invites/page.tsx
Add logging of query parameters and validation output to the invites page for debugging purposes.
The changes are intended to aid in diagnosing issues with the invite process by outputting relevant details of the query parameters and the results of their validation, which can assist in determining any discrepancies or issues within the invite handling logic.
=> chore(gtm): [on-3718] invite fix

app/src/app/[lng]/organization/invites/page.tsx, app/src/app/[lng]/user/invites/page.tsx
Fix email input sanitation by correctly handling email addresses that include a plus (`+`) sign.
Emails often contain plus signs, which were not handled correctly by previous input sanitation processes, potentially causing errors in invite acceptance functions. This update ensures email inputs with plus signs are sanitized and processed correctly, thus improving the functionality and reliability of the invite feature. Additionally, this PR includes some minor cleanup by removing console logs that are no longer necessary.
=> fix(gtm): sanitize email inputs with + correctly

app/src/backend/RoleBasedAccessService.ts, app/src/backend/UserService.ts
Include inventory access for organization-level users by introducing access checks for users with organizational ownership in the `UserService.ts` file.
To enhance access control by allowing users with organization-level permissions to access inventories, improving the flexibility and scalability of user permissions across projects and organizations. This approach ensures that users with higher-level access have appropriate permissions to manage and view inventories, overcoming existing limitations where only city-level user access was checked.
=>  include inventory access for org level users

.github/workflows/web-develop.yml, app/src/app/[lng]/onboarding/setup/page.tsx, app/src/components/ClientRootLayout/index.tsx, app/src/components/HomePage/Hero.tsx, app/src/components/HomePage/HomePage.tsx, app/src/components/steps/select-city-steps.tsx, app/src/util/feature-flags.ts
also, store feature flags in enum.
Hide the "Project Overview" link behind a feature flag and refactor feature flags to use an enumeration for consistency across the codebase.
The addition of a feature flag for "Project Overview" ensures that the feature can be toggled in different environments seamlessly, allowing for controlled rollout and testing. Refactoring the feature flags to an enumeration improves code maintainability and reduces the potential for errors by centralizing flag management and enforcing consistent usage across the application code.
=> bug (project overview): [ON-3823] hide Project overview link behind FF

app/src/components/ClientRootLayout/index.tsx
Add a temporary condition to include roles with type `User` in the access verification logic of the `ClientRootLayout` component.
This change is required to allow user roles to have access during development while a more permanent solution for handling new user access is being created. The comment indicates that this condition is intended to be temporary and will be removed once an improved access management system is implemented.
=> fix: adds temp condition to include roles with type user

app/package-lock.json, app/package.json, app/tests/tsconfig.json, app/tsconfig.json
Now using Playwright instead
Remove the unused package `cypress` from `package.json` and `package-lock.json`.
The `cypress` package is no longer being utilized in the project, removing it helps in reducing dependency bloat and potential security vulnerabilities associated with outdated or leftover packages.
=> chore(deps): remove unused package cypress

app/src/app/api/v0/inventory/[inventory]/download/route.ts, app/src/app/api/v0/projects/[projectId]/bulk-download/route.ts, app/src/backend/AdminService.ts, app/src/backend/CSVDownloadService.ts, app/src/backend/InventoryDownloadService.ts, app/src/backend/UserService.ts
New API route `/api/v0/projects/[projectId]/bulk-download` allows downloading the data from all inventories in a project in a single CSV file.
Add functionality for bulk downloading project inventories in CSV format and refactor inventory data retrieval logic to enhance code reusability.
This change addresses the need for a bulk download feature for project inventories, facilitating administrative tasks while streamlining the data retrieval process. The inclusion of a dedicated service for querying inventory data improves maintainability by encapsulating related logic, reducing code duplication across the application.
=> feat(api): ON-3839 bulk project CSV download

app/src/i18n/locales/en/data.json, app/src/util/form-schema/manual-input-hierarchy.json
Add new waste composition values such as "leather", "plastics", "metal", "glass", "nappies", and "other" to both the English localization data and the manual input hierarchy JSON schema.
These additions provide a more comprehensive categorization of waste types in the application, enhancing its ability to accurately represent diverse waste management scenarios. This change is necessary for improving the user experience by covering broader waste composition categories.
=> feat: waste composition values added

.github/workflows/web-develop.yml
Add `ACCOUNT_SETTINGS_ENABLED` to the `NEXT_PUBLIC_FEATURE_FLAGS` in the `web-develop.yml` file for the development environment.
This change is being made to enable the Account Settings feature flag in the development environment, allowing developers to test and work on account settings functionality before it is released to production.
=> [ON-3858] add ACCOUNT_SETTINGS_ENABLED to dev environment

app/src/backend/CSVDownloadService.ts, app/src/util/types.ts
Enhance the CSV download functionality by incorporating third-party data into the CSV output.
This change addresses the issue where third-party data was previously missing from the CSV downloads, ensuring the CSV file now includes comprehensive activity records with corresponding emissions factors and data source details. The newly added types and refactored code help maintain cleaner and more organized data handling, improving overall maintainability and readability.
=> fix(api): ON-3926 CSV download not containing third party data

.github/workflows/web-tag.yml, app/package.json, app/scripts/generate-changelog.js
Extend GitHub workflows to include a new changelog generation process, improve deployment configurations, and enhance email sending functionality with comprehensive logging and error handling.
The changes are introduced to automate changelog creation using OpenAI's API for improved release communication, enhance deployment efficiency by refining deployment scripts, and increase email system reliability and traceability with detailed logging. This enables better tracking of application updates, reduces human error in manual changelog creation, and ensures the email system's robustness.
=> Nina/feat/on 3808/changelog

app/tests/api/organization_invite.jest.ts
Adjust the test object names in the organization invite test to include identifier suffixes for better test distinction.
The changes improve clarity and specificity in test data naming, which helps differentiate between test runs and scenarios, particularly useful when running these tests in continuous integration environments. The additional identifiers also make it easier to track test emails and debug potential issues by clearly associating them with a specific test context.
=> fix(ci): adjust names for test objects in org invite test

app/src/i18n/locales/de/manage-subsectors.json, app/src/i18n/locales/en/manage-subsectors.json, app/src/i18n/locales/es/manage-subsectors.json, app/src/i18n/locales/pt/manage-subsectors.json
Changes
- Adds translations for the update button text
Add translations for the "Update" button in the German, English, Spanish, and Portuguese localization files.
This change ensures that the "Update" button is properly translated across all supported languages, improving the user interface and experience for non-English speaking users. Existing translations were incomplete and required updates to include this crucial interface component.
=> fix(i18n): adds translations for the update button

app/src/components/HomePage/HomePage.tsx, app/src/components/Modals/delete-city-modal.tsx, app/src/components/Modals/delete-inventory-modal.tsx, app/src/services/api.ts
Correct error handling for missing verification token and inventory error on the homepage and modal dialog components by updating query hooks and adjusting the error flow logic in `HomePage.tsx` and `delete-inventory-modal.tsx`, including a typo fix in API service.
Users were getting locked out when deleting the default inventory due to inadequate error handling, such as missing verification tokens and inventory errors were not being properly managed. These changes aim to improve user experience by ensuring smoother navigation to onboarding in case of errors and correcting the typo in the API query to prevent potential usage errors.
=> fix(ui): ON-3898 locked out when deleting the default inventory

app/src/app/api/v0/emissions-factor/route.ts
Implement a geographical hierarchy system to match Emissions Factors (EFs) more accurately, with priority given to regions, cities, countries, and globally as a fallback.
These changes enhance the logic for filtering and ranking emissions factors by geographical location, addressing technical debt by unifying and prioritizing the hierarchy, thereby making the selection process more precise and intuitive.
=> (Tech-debt):  match EFs by geographical heirachy

app/src/components/Modals/activity-modal/activity-modal-body.tsx
Refactor the UI to fix the obstructed unit dropdown by utilizing `HStack` for layout, ensuring dropdown fields have a minimum width and border styles for better visibility and handling form errors.
The previous implementation caused the unit dropdown to be obstructed, leading to poor user experience. By using `HStack` and adjusting styling properties like minimum width and border handling, the UI now facilitates a clearer, more accessible interaction with the dropdown, addressing issue ON-3902.
=> fix(ui): ON-3902 obstructed unit dropdown

app/migrations/20250602124552-add_active_column_to_org_table.cjs, app/package-lock.json, app/src/app/[lng]/admin/page.tsx, app/src/app/api/v0/organizations/[organizationId]/active-status/route.ts, app/src/app/api/v0/organizations/route.ts, app/src/backend/EmailService.ts, app/src/i18n/locales/en/admin.json, app/src/lib/emails/AccountUnFrozenNotificationTemplate.tsx, app/src/models/Organization.ts, app/src/services/api.ts, app/src/util/types.ts, app/src/util/validation.ts, app/tests/api/city_transfer.jest.ts, app/tests/api/organization.jest.ts, app/tests/api/organization_invite.jest.ts, app/tests/api/organizations.jest.ts, app/tests/api/project.jest.ts
Add functionality to freeze and unfreeze organization accounts, including database schema changes, API endpoints, email notifications, and user interface updates to toggle organization active status.
These changes address a need for administrators to manage organization account statuses directly within the application, allowing them to freeze accounts if necessary due to security or compliance reasons and reactivate them when appropriate. The implementation involves adding an 'active' field to the Organization model, creating new endpoints to handle the status updates, sending notifications to users, and adapting the UI to reflect these options, ensuring a seamless administrative experience. …
=> feat: on-3865-freeze-organization-accounts

app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeViewSourceDrawer.tsx, app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx, app/src/app/[lng]/[inventory]/data/[step]/SourceDrawer.tsx, app/src/app/[lng]/[inventory]/data/[step]/SourceDrawerActivityTable.tsx, app/src/app/[lng]/[inventory]/data/[step]/page.tsx, app/src/app/api/v0/datasource/[inventoryId]/datasource/[datasourceId]/route.ts, app/src/app/api/v0/datasource/[inventoryId]/route.ts, app/src/backend/DataSourceService.ts, app/src/backend/ResultsService.ts, app/src/i18n/locales/en/dashboard.json, app/src/i18n/locales/en/data.json, app/src/services/api.ts, app/src/util/types.ts, app/tests/api/datasource.jest.ts
Add the functionality to include source details in the report results within the Inventory Result Tab by integrating a source drawer to display detailed information of data sources.
These changes are being made to provide users with detailed visibility of underlying data sources in report results, addressing user feedback on the transparency and traceability of data. This enhancement improves the user experience by allowing them to directly access data source details from the inventory results. The best approach was to utilize React components like `useDisclosure` for managing the drawer's open state and integrate these functionalities via API modifications that fetch and display source data accordingly. …
=> feat(report results) [ON-3923]: sourceDetailsInReportResults

app/package-lock.json, app/src/app/api/v0/city/[city]/file/route.ts, app/src/app/api/v0/city/route.ts, app/src/app/api/v0/city/transfer/route.ts, app/src/app/api/v0/organizations/[organizationId]/route.ts, app/src/app/api/v0/projects/[projectId]/route.ts, app/src/backend/EmailService.ts, app/src/components/Modals/add-file-data-dialog.tsx, app/src/lib/emails/CitiesAddedToProjectNotification.tsx, app/src/util/constants.ts, app/tests/api/organization.jest.ts, app/tests/api/user_file.jest.ts, app/tests/helpers.ts
Implement bug fixes and feature enhancements for City Catalyst, including file validation, email notifications for project changes, and restrictions on default organization and project modifications.
The changes are necessary to improve file handling by enforcing size and format validation, ensure proper notification via email when cities are added or transferred to projects, and prevent unintended updates or deletions of default organization and project data. These updates enhance user experience and data integrity within the application.
=> fix:  city catalyst bug fixes

app/src/app/[lng]/[inventory]/data/manage-sectors/SectorTabs.tsx
Changes
- adds conditions to show toast properly
- adds duration to toaster
Set correct conditions to display a success toaster message by checking if the loading is complete and there is no error after updating notation keys.
The previous condition did not adequately verify that the operation was complete and without errors before displaying the success message, which could mislead the user. Adding checks for `!isLoading` and `!isError` ensures the toaster message is only shown when the update is truly successful and stable.
=> sets correct conditions to show toaster message

app/src/app/[lng]/[inventory]/data/manage-sectors/SectorTabs.tsx
Changes
- Adds opacity to checkbox component, this increases component visibility.
Add opacity and secondary content color to the CheckboxCard.Description component in the SectorTabs component.
The opacity and color adjustments enhance the UI by ensuring the checkbox descriptions are consistently visible and in line with the overall design theme. This change addresses a visual inconsistency, improving readability and user experience.
=> fix(ui): adds opacity to checkbox description component

app/src/i18n/locales/de/settings.json, app/src/i18n/locales/es/settings.json, app/src/i18n/locales/fr/settings.json, app/src/i18n/locales/pt/settings.json
Add translations for plan details and related strings in German, Spanish, French, and Portuguese settings JSON files.
These changes are necessary to ensure the application supports multilingual users by providing localized text for displaying plan details and upgrade prompts. This is part of an ongoing effort to enhance user experience across different languages.
=> fix(ui): ON-3858 plan details translations

app/src/app/[lng]/organization/[id]/account-settings/team/index.tsx, app/src/components/HomePage/AddCollaboratorModal/AddCollaboratorsModal.tsx, app/src/hooks/organization-context-provider/use-organizational-context.tsx, app/src/i18n/locales/en/settings.json
Modify the Add Collaborator modal to accurately reflect user-specific projects by replacing `useGetProjectsQuery` with `useGetUserProjectsQuery`, adjust CSS alignment in TeamSettings component, fix organizational context state update to maintain active status, and improve localization strings.
These adjustments were made to address a bug where incorrect projects were shown when adding collaborators, enhance the user interface alignment in the team settings, and ensure correct context update behavior. The localized settings were refined for clearer user prompts and to support additional themes. These changes enhance accuracy, user interaction, and maintainability of the application. …
=> fix: [on-4167] fixes project drawer in add collaborator modal

app/Dockerfile, app/src/backend/ECRFDownloadService.ts
Fix the ECRF file download by ensuring the correct path is used to locate the eCRF template and add the template directory to the Docker build process.
The path to the eCRF template file was incorrectly configured, leading to file-not-found errors; the new logic constructs the file path dynamically and verifies its existence, while changes to the Dockerfile ensure the template directory is included in the build for accessibility.
=> fix: [on-4165] fix ecrf file download

app/e2e/helpers.ts, app/e2e/signup.spec.ts, app/src/app/[lng]/[inventory]/data/[step]/page.tsx, app/src/app/[lng]/auth/signup/page.tsx, app/src/components/navigation-bar.tsx, app/src/util/validation.ts
Remove the invite code functionality from the sign-up page, adjust the file upload logic in the sector file component to handle files, and update the navbar logo styling with improved object fitting and dimensions.
The invite code feature is deprecated and no longer necessary, thus simplifying the sign-up process. The sector file upload feature required refinement to ensure files are properly handled upon selection. The navbar logo update ensures better visual alignment and presentation with the styling changes.
=> feat:  ui changes to sign up page, navbar and sector file upload

app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx
https://jam.dev/c/423c6ecc-f3ff-4c9a-b59c-067bf015d274
Refactor the Docker build and push process, enhance the `ByScopeView` component by grouping data by subsector, handle error logging and path construction in `ECRFDownloadService`, and update multiligual settings in various locales.
These changes streamline the Docker image handling process with more efficient version extraction and usage of GitHub Actions, improve the user interface by making data more manageable and organized in the `ByScopeView` component by grouping items, improve error handling and file path management in `ECRFDownloadService` for better reliability and logging, and expand translations by adding necessary context for new features across multiple languages. This approach provides better maintainability, user …
=> [ON-4169] group by subsector

app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx, app/src/i18n/locales/de/dashboard.json, app/src/i18n/locales/en/dashboard.json, app/src/i18n/locales/es/dashboard.json, app/src/i18n/locales/fr/dashboard.json, app/src/i18n/locales/pt/dashboard.json
fix percentage calculation
Fix the bug in the `ByScopeView` component by correctly calculating the percentage of total emissions for subsectors relative to the sector total.
The previous implementation inaccurately calculated the percentage of emissions by summing up predefined percentage values, which could lead to incorrect results. The updated logic ensures accurate calculations by utilizing actual emission values across subsectors, addressing inaccuracies and improving data reliability for users.
=> [ON-4169] group by subsector - bugfix

app/src/app/api/v0/city/route.ts, app/src/app/api/v0/city/transfer/route.ts
Fix translation of cities added email, improve error handling, update dependencies, and enhance UI and API functionalities across several modules.
The changes address various issues including translation inaccuracies, security concerns with a silent failure for non-existent user email responses during password reset, navigation improvements on invite acceptance, and the addition of the user's preferred language attribute in APIs for better internationalization support. Dependency updates for improved library functions and bug fixes are also incorporated, along with UI improvements like handling form switch events correctly and making the organization state management more accurate. Additionally, minor code cleanups and usability enhancements are implemented for a better user interface and …
=> Hotpatch/nina/bug/on 4053/fix translation of cities added email

app/src/app/api/v0/city/route.ts, app/src/app/api/v0/city/transfer/route.ts
Extend user query attributes by adding "preferredLanguage" to both the city and city transfer API routes.
These changes support the retrieval of users' preferred languages, enabling the translation of city-added emails to be dynamically adapted based on user language preferences, thereby enhancing email localization and user experience.
=> fix(email) [ON-4053]: fix translation of cities added email

app/src/app/[...not_found]/layout.tsx, app/src/app/[lng]/layout.tsx, app/tests/api/datasource.jest.ts
Add `suppressHydrationWarning` to HTML elements in layout files and re-enable a previously skipped test suite for the DataSource API.
To resolve hydration issues during server rendering by suppressing related warnings, ensuring consistent user experience across different locales in the application. Re-enabling the DataSource API test suite helps in maintaining code quality by ensuring that all functionalities continue to work as expected post-changes.
=> fix: on-4139-hydration-issue

app/src/components/HomePage/HomePage.tsx
Integrate logging for error handling in the HomePage component and update the redirection logic when inventory issues arise.
The changes enhance error logging and debugging capabilities by utilizing the logger service to provide detailed error reports when inventory fails to load, and include console warnings for missing inventory IDs. This allows for improved monitoring and quicker identification of issues, addressing the ON-4187 bug regarding login to onboarding transition for existing users.
=> fix(ui): ON-4187 going from login to onboarding for exisiting user

app/src/backend/UnitConversionService.ts
Add propane fuel density to the `UnitConversionService`.
The addition of propane fuel density enables accurate unit conversions for applications involving propane as a fuel type, addressing the need for more comprehensive fuel density data within the `UnitConversionService`. This update resolves any gaps previously impacting calculations reliant on propane measurements, thereby enhancing the service's overall utility and reliability.
=> fix(api): ON-4328 add propane fuel density to UnitConversionService

app/migrations/20250721185038-Module_create.cjs, app/migrations/20250721185138-ProjectModules_create.cjs, app/migrations/20250721192636-Module_backfill.cjs, app/src/app/api/v0/modules/route.ts, app/src/app/api/v0/projects/[project]/modules/route.ts, app/src/models/Module.ts, app/src/models/ProjectModules.ts, app/src/models/init-models.ts, app/src/services/api.ts
Add new database migrations for creating `Module` and `ProjectModules` tables, along with their respective indexes.
These changes are necessary to establish new database tables that will support the application's module management feature. This approach allows efficient querying by creating indexes on frequently searched columns, optimizing data retrieval operations related to modules and their associations with projects.
=> feat [ON-4317] [ON-4318](JN) - db migrations

app/src/lib/emails/CitiesAddedToProjectNotification.tsx, app/src/lib/emails/InviteUserToMultipleCitiesTemplate.tsx, app/src/lib/emails/RemoveUsersFromMultipleCities.tsx, app/src/lib/emails/RoleUpdateNotificationTemplate.tsx
Refactor email templates to conditionally load brand logos and adjust styling to ensure logos appear correctly in invitation and project emails.
To fix the issue of missing logos in the invitation and project emails by dynamically displaying the brand logo if available, or substituting it with a brand text if not. This approach improves the visual consistency of the emails and accommodates situations where logos might not be available.
=> fix: [on-4229] Missing Logos in Invitation and Project Emails

app/migrations/20250729154852-ProjectModules_backfill.cjs
* use sequelize instead of raw query (PR feedback)
* grant all users access to GHGI, not HIAP. (no worries, the page is hidden outside of dev anyways, so people won't be able to access)
Add a backfill migration script to adjust modules in the "ProjectModules" table and update the "Module" table's stage values; refactor the `updateDefaults` method in `UserService.ts` to use Sequelize's ORM approach.
The migration addresses specific data inconsistencies and ensures that the module data reflects the correct relationships and naming conventions, hence maintaining data integrity. The refactoring in `UserService.ts` improves code readability, leverages Sequelize's ORM capabilities for better maintainability, and reduces raw SQL query dependency.
> Is this description stale? Ask me to generate a …
=> Bug/nina/on 4302/last fixes on home page

app/src/app/[lng]/onboarding/setup/page.tsx
Changes
- Adds text color to back button
- Adds container size to page wrapper
=> fix: ON-4406 restores back button on dashboard

app/src/app/[lng]/onboarding/done/[cityId]/[year]/[inventory]/page.tsx
Changes
- Adds correct path for done page image asset
Update the background image path in the `OnboardingDone` component from `'/images/city-bg.png'` to `'/assets/city_vector_onboarding.svg'`.
The image asset path was incorrect, leading to display issues during the onboarding process. The correct path ensures the appropriate image is shown, enhancing the visual experience and consistency across the application.
=> fix: adds correct image asset path

app/src/app/api/v0/projects/[project]/modules/route.ts
Correct the variable name to `project` in the route validation schema and update its reference in the parsing of API request parameters.
The code previously incorrectly used `projectId` instead of `project`, causing validation issues with project ID parsing. This change aligns the variable names for consistency and fixes the validation process to ensure API requests are handled with the correct parameters.
=> fix [ON-4333](JN): fix variable name in route validation

app/package.json, app/scripts/emissions-factors-sync.ts, app/seeders/20231114094254-emissions-factors.cjs, k8s/cc-sync-catalogue-manual.yml, k8s/cc-sync-catalogue.yml, k8s/prod/cc-prod-sync-catalogue.yml, k8s/prod/cc-sync-catalogue-manual.yml, k8s/test/cc-test-sync-catalogue.yml
Set up and integrate an Emissions Factors (EF) synchronization script into the current codebase, including updates to the package scripts, seeders, and Kubernetes configurations.
The introduction of the `emissions-factors-sync.ts` script is to automate the synchronization of emissions factors data from an external API, addressing technical debt by replacing manual seeding processes. This approach ensures real-time data accuracy and is better suited for scaling operations by utilizing an API-driven workflow while deprecating the outdated seeding strategy. Kubernetes configurations were updated to incorporate this script into existing deployment processes for consistent execution environments. …
=> feat: (tech debt) [on-4285] set up EF sync

app/migrations/20250811001707-oauth-client-table.js, app/src/app/api/v0/client/[client]/route.ts, app/src/app/api/v0/client/route.ts, app/src/models/OAuthClient.ts, app/src/models/OAuthClientI18N.ts, app/src/models/init-models.ts, app/src/util/feature-flags.ts, app/tests/api/oauth_client.jest.ts
Database, ORM, and API endpoints for OAuth clients.
Add OAuth client management functionality, including creating, retrieving, and deleting OAuth clients, with internationalization support for client names and descriptions.
These changes implement OAuth 2.0 client management to enable secure and scalable provider-client interactions while supporting multiple languages for client metadata. This update addresses the need for robust authentication and authorization handling within our system, promoting better user management and integration with third-party systems.
=> OAuth Client Management

app/src/i18n/locales/de/data.json, app/src/i18n/locales/en/data.json, app/src/i18n/locales/es/data.json, app/src/i18n/locales/fr/data.json, app/src/i18n/locales/pt/data.json
Add missing translation for "treatment-type-latrine" key across all language JSON files.
The "treatment-type-latrine" key was missing from the translation files, leading to incomplete localization support; these additions ensure consistency and completeness in the app's multilingual capabilities.
=> fix: adds missing translations

app/src/components/CookieConsent/index.tsx, app/src/instrumentation-client.ts, app/src/lib/analytics.ts
Update feature flag check from `hasServerFeatureFlag` to `hasFeatureFlag` and modify analytics initialization to wait for the environment variables to be available before starting.
The previous implementation did not properly resolve feature flags due to server-side checks, resulting in analytics functionalities not being initialized correctly. This update ensures the client environment has been set before initializing analytics, using `hasFeatureFlag` for accurate flag resolution and checking environment readiness with a polling mechanism.
=> fix: resolve issues with feature flags not resolving for analytics

app/src/backend/ResultsService.ts
In report results view on prev. dashboard and new JN dashboard (because API routes were fixed).
When there are no ActivityValues in the InventoryValue, use the InventoryValue's co2eq property instead of assuming 0
Ensure IV-level `co2eq` values are included in the emissions breakdown calculation when there are no associated activity-level values.
Previously, the calculation only considered the `co2eq` from activities, neglecting cases where inventory values had a direct `co2eq` value without associated activities, leading to incomplete emissions data. This alteration corrects the logic to include the `co2eq` from the inventory value itself if no activities are present, thus ensuring accurate emissions reporting.
> Is this description stale? Ask me to generate a new description by …
=> fix(api): ON-4482 IV-level co2eq ignored in breakdown

app/e2e/dashboard.spec.ts, app/e2e/helpers.ts, app/e2e/login.spec.ts, app/e2e/third-party-datasets.spec.ts, app/src/app/[lng]/[inventory]/data/[step]/page.tsx
Add comprehensive end-to-end tests for third-party data sources interaction using Playwright.
To ensure reliable functionality for creating city inventories, navigating through various data sectors, and managing connections to third-party data sources. These tests validate expected behaviors such as searching, connecting, disconnecting, and persisting data source connections across navigations and page refreshes, aiding in regression prevention and improving application stability.
=> fix: e2e [4991] third party data sources e2e

app/package-lock.json, app/package.json
Update the `eslint` and `ts-jest` dependencies in `package.json` and `package-lock.json`, remove several unused modules, and add new modules `handlebars`, `uglify-js`, and `wordwrap`.
These changes resolve build issues in the global dashboard by updating dependencies to their appropriate ranges to maintain compatibility and security, while removing outdated or unnecessary packages to streamline the build process. The addition of new modules helps address unmet peer dependency issues and ensures smoother operation.
=> fix: build fix for global dashboard

app/src/components/Tabs/my-inventories-tab.tsx
Add fallback checks for country locode in `MyInventoriesTab`, remove custom invite error handling, and clean up associated translations and error handling.
The changes are implemented to ensure consistent fallback behavior when country locode is unavailable and to simplify error handling by removing unnecessary custom invite error logic. The cleanup of translations reflects the removal of obsolete error handling, reducing clutter and potential confusion in the codebase.
=> fix: (CC_Maintenance) [on-4357]  add fallback checks for country locode

app/src/app/api/v0/inventory/[inventory]/hiap/route.ts, app/src/backend/EmailService.ts, app/src/backend/hiap/HiapService.ts, app/src/i18n/locales/en/emails.json, app/src/lib/emails/HiapRankingReadyTemplate.tsx
Changes
- Adds email template for HIAP
- Adds helper function in HIAP service to trigger emails after ranking is ready
- Adds translation strings
Add a new email template to notify users when High Impact Action Plan (HIAP) rankings are ready, integrate the template into the email service, and modify the existing process to trigger email notifications when actions are ranked successfully.
These changes aim to improve user experience by proactively notifying users when their requested data processing is completed and ready for viewing. This enhancement respects user engagement by providing timely updates and directs them back to the platform to explore the results, helping promote active usage and involvement with the application.
> Is this description stale? Ask me to generate a new …
=> adds email template to send emails once actions are ranked

app/src/app/[lng]/[inventory]/data/[step]/page.tsx, app/src/app/[lng]/[inventory]/data/[step]/types.ts, app/src/components/ChatBot/chat-bot.tsx, app/src/services/api.ts
Refactor the progress bar logic to allow it to decrease and clean up formatting and imports across multiple components.
The progress bar was previously unable to decrease because it was using `Math.max` to clamp progress state; this issue was fixed by directly assigning clamped progress values to reflect user actions more accurately. Additionally, code formatting consistency and import optimizations improve maintainability and readability across the application.
=> fix(ui): ON-4565 progress bar not able to go down, only up 📈

app/src/i18n/locales/de/dashboard.json, app/src/i18n/locales/en/dashboard.json
Translation strings for other languages will be added by translation PR bot.
=> fix(i18n): adds missing translation string for publish button

.github/workflows/web-develop.yml, app/.gitignore, app/e2e/city-onboarding.spec.ts, app/e2e/csv-download.spec.ts, app/e2e/global-setup.ts, app/e2e/helpers.ts, app/next.config.mjs, app/playwright.config.ts, app/public/openapi-spec.json, app/src/app/api/v0/admin/all-cities/route.ts, app/src/app/api/v0/admin/bulk/route.ts, app/src/app/api/v0/assistants/threads/export/route.ts, app/src/app/api/v0/city/[city]/file/route.ts, app/src/app/api/v0/city/[city]/inventory/route.ts, app/src/app/api/v0/city/[city]/modules/hiap/dashboard/route.ts, app/src/app/api/v0/city/[city]/years/route.ts, app/src/app/api/v0/waste-composition/route.ts
Also fixes issues in a lot of YAML comments and hides them from CI output for now.
=> fix(test): dismiss cookie consent overlay in Playwright tests

app/src/components/GHGIHomePage/DownloadAndShareModals/ModalPublish.tsx
Changes
- Adds fit content to prevent view-site button from overflowing
=> fix: adds fit-content to prevent view site button from overflowing

app/package.json, app/scripts/update-country-emissions.ts
Changes
- Adds script to fetch and update total country emissions
=> feat: adds script to populate brazilian cities with total Emissions
